### ISSUE TITLE
Not works with Java 7

### ISSUE THREAD

**Issue by JohnWu-Pro** [jgitver/jgitver-maven-plugin#11]
When running Maven 3.3.9 under Oracle JDK 1.7.0_79, the following error shows up

> [WARNING] Error injecting: fr.brouillard.oss.jgitver.JGitverExtension
> java.lang.TypeNotPresentException: Type fr.brouillard.oss.jgitver.JGitverExtension not present
>         at org.eclipse.sisu.space.URLClassSpace.loadClass(URLClassSpace.java:147)
>         at org.eclipse.sisu.space.NamedClass.load(NamedClass.java:46)
>         at org.eclipse.sisu.space.AbstractDeferredClass.get(AbstractDeferredClass.java:48)
>         at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
>         at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:53)
>         at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInternalFactory.java:65)
>         at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:115)
>         at org.eclipse.sisu.bean.BeanScheduler$Activator.onProvision(BeanScheduler.java:176)
>         at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:126)
>         at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:68)
>         at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:63)
>         at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
>         at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
>         at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
>         at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
>         at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
>         at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
>         at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
>         at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
>         at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
>         at org.eclipse.sisu.inject.LazyBeanEntry.getValue(LazyBeanEntry.java:81)
>         at org.eclipse.sisu.plexus.LazyPlexusBean.getValue(LazyPlexusBean.java:51)
>         at org.eclipse.sisu.wire.EntryListAdapter$ValueIterator.next(EntryListAdapter.java:111)
>         at java.util.AbstractCollection.addAll(AbstractCollection.java:341)
>         at org.apache.maven.DefaultMaven.getLifecycleParticipants(DefaultMaven.java:400)
>         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:262)
>         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
>         at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
>         at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
>         at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
>         at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:606)
>         at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
>         at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
>         at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
>         at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
> Caused by: java.lang.UnsupportedClassVersionError: fr/brouillard/oss/jgitver/JGitverExtension : Unsupported major.minor version 52.0
>         at java.lang.ClassLoader.defineClass1(Native Method)
>         at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
>         at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
>         at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
>         at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
>         at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
>         at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
>         at java.security.AccessController.doPrivileged(Native Method)
>         at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
>         at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClassFromSelf(ClassRealm.java:401)
>         at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:42)
>         at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
>         at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
>         at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
>         at org.eclipse.sisu.space.URLClassSpace.loadClass(URLClassSpace.java:139)

**Comment by McFoggy** [comment]
jgitver requires java >= 1.8
