### ISSUE TITLE
Stuck in loop

### ISSUE THREAD

**Issue by jschneider** [jgitver/jgitver-maven-plugin#110]
I upgraded my project to 1.4.4

Invoking maven results in a loop with that kind of stack trace:

```
	at fr.brouillard.oss.jgitver.GitVersionCalculator.lookupCommits(GitVersionCalculator.java:365)
	at fr.brouillard.oss.jgitver.GitVersionCalculator.lookupCommits(GitVersionCalculator.java:365)
	at fr.brouillard.oss.jgitver.GitVersionCalculator.lookupCommits(GitVersionCalculator.java:365)
```

The commit ids in each call are different. I don't know what might have changed. But obviously the code takes a lot of time now compared to previous versions.

More details:
1.4.3 - 1.4.4: Takes ages for the loop. Probably will result in a StackOverflowError some time (did not wait longer than maybe 5 minutes)
1.4.0-1.4.2: Runs into a StackOverflowError almost immediately at fr.brouillard.oss.jgitver.GitVersionCalculator.lookupCommits(GitVersionCalculator.java:354)
1.3.0: Works fine

**Comment by McFoggy** [comment]
use `maxSearchDepth` config for the moment please.

```
<configuration>
    <maxSearchDepth>100</maxSearchDepth>      // put whatever number best fits your project
</configuration>
```

since jgitver/jgitver#49 we try to lookup all branches (included merged ones) to find relevant tags for version computation.
please see [this comment](https://github.com/jgitver/jgitver-maven-plugin/issues/101#issuecomment-445167260)

**Comment by jschneider** [comment]
In my project I have to set the max search depth to "10".

If the max search depth is set to "50", a simple "mvn validate -N" takes more than 6 seconds.
So for the moment this is a workaround, but I think there should be done something about that.

**Comment by McFoggy** [comment]
@jschneider do you have the possibility to share your project?

> If the max search depth is set to "50", a simple "mvn validate -N" takes more than 6 seconds.

Ouch!!! how many merges do you do without rebase on this project?

> but I think there should be done something about that.

I agree

**Comment by McFoggy** [comment]
can you please execute the following command and attach the result file here?

```
git log --no-color --graph --pretty=format:"%h -%d" --abbrev-commit > history.txt
```

It just log your commit IDs in a graph with the tags associated if there are some. It does not leak any information on your project.

**Comment by jschneider** [comment]
I do not have too many complex merges (at least I think).
We try to follow the Rebase-Merge-workflow.

But I have integrated a lot of projects into one repository some time ago. So maybe that might be the reason?

[history.txt](https://github.com/jgitver/jgitver-maven-plugin/files/2713441/history.txt)

**Comment by McFoggy** [comment]
Hi Johannes,

thanks a lot for the file with the commits.

Can I ask you please to perform also the following commands please?
```
$ git log --oneline | wc -l
$ git log --oneline | grep "tag:"
```

Is it really on this project that you had to set the max search depth to "10"?

I urgently need to fix the current behavior because the parsing of the branches is currently exponential.
I have created jgitver/jgitver#67 to track it.

**Comment by jschneider** [comment]
git log --oneline | wc -l:
21791

the other command doesn't work for me. Grep doesn't find the tags. Sorry.
And yes - this is the repository that gets very, very slow.

**Comment by McFoggy** [comment]
> the other command doesn't work for me. Grep doesn't find the tags. Sorry.

it means that if we 'just' follow direct parents on the same branch ; without looking at merged branches ; we cannot find any tag in your repository.

**Comment by jschneider** [comment]
Don't think so. The output of git log --oneline *does* show tags.  They just don't show up when grepping for them. Maybe something related to the colored output?

**Comment by McFoggy** [comment]
if you redo with `--no-color`?

**Comment by jschneider** [comment]
nope.
The point is: piping the output of "git-log --oneline" the branch names / tags are never printed.

**Comment by McFoggy** [comment]
use the following `git log --no-color --graph --pretty=format:"%h -%d" --abbrev-commit | grep "tag:"`
Then compare this to `git tag --list`.  
The first will give the tags reachable via direct parent link, the other will print all tags in the repo.  

Looking at your [history](https://github.com/jgitver/jgitver-maven-plugin/files/2713441/history.txt) file it looks like all tags come from merged branches (or _rebase with merges_ which is more or less the same).
In your case no doubt that we MUST look at merged branches.

**Comment by jschneider** [comment]
I don't exactly understand what you are looking for.

git tag --list returns 364 tags
git log --no-color --graph --pretty=format:"%h -%d" --abbrev-commit | grep "tag:"
returns 358 tags. 

I can't figure out exactly which tags are missing. But it looks like "git tag --list" returns all tags that are relevant for jgitver.
So I think I am missing the bigger point here. Could you help me there?

**Comment by McFoggy** [comment]
I released this morning jgitver-maven-plugin-1.4.5 based on jgitver-0.9.0 which improves computation.

On spark project _(which tagging model is really not for use with jgitver)_, using one of the latest commit, here is what I obtain

![image](https://user-images.githubusercontent.com/1119660/50764552-4fbf8000-1273-11e9-9e9e-be747e160d82.png)

the configuration used with latest jgitver-maven-plugin-1.4.5 is

```
<configuration>
    <mavenLike>false</mavenLike>
    <autoIncrementPatch>true</autoIncrementPatch>
    <useCommitDistance>true</useCommitDistance>
</configuration>
```

**Comment by jschneider** [comment]
I updated to 1.4.5. and am using the suggested configuration:

First the good message: It takes 1312ms - which is acceptable.

Unfortunately the output does not make any sense for my project. JGitver creates the version "2013.0.0-SNAPSHOT" which is not what I expect. The old versions of jgitver calculate the version "8.7.1-SNAPSHOT" which is correct.

Running with "-X" tells me that jgitver uses the base tag "2013-04-28" which is as old as it sounds. That tag has been created in a repository which has later been merged into the main repository. So maybe it is related to that?
Another idea: Are the tags sorted by number?

For me the behavior for jgitver always made a lot of sense: So I don't exactly get what the newer versions try to accomplish with the changed behavior.

**Comment by McFoggy** [comment]
indeed your project history is the culprit of jgitver current behavior.

I see 2 options for your case:

- rename the tags that do not correspond anymore to some project versions
- setup jgitver and change the tag detection regexp to refine the 'version tags' jgitver will use
    - use `regexVersionTag` configuration property for that. There you can replace the default regexp with one more accurate for your use case that will exclude tags of the form _2013-04-28_ for example. Take care that a capture group is required in the regexp.

**Comment by McFoggy** [comment]
based on the history file you have already provided above I would suggest to start with the following regexp : `^(?![4567][0-9]\.)((?:[0-9]+\.[0-9]+\.[0-9]+)(?:-.*)?)$`

I tested it under RegexBuddy and it looks to bring good results. It keeps only version of kind 'X.Y.Z-whatever' but it excludes correctly all your tags 2012, 2013 and the ones starting with numbers between 40 & 79.

**Comment by jschneider** [comment]
Can you explain why the tag "2013-04-28" is used? And not the nearer tag 8.7.0?

**Comment by McFoggy** [comment]
> Can you explain why the tag "2013-04-28" is used? And not the nearer tag 8.7.0?

of course.

- jgitver, using a configurable regexp, identifies version tags i.e. tags that correspond to a version. By default the pattern recognizes version that look like:
  - X
  - X-something
  - X.Y
  - X.Y-something
  - X.Y.Z
  - X.Y.Z-something
- once all repository 'version tags' are identified, they are filtered to keep only the reachable ones from the current HEAD
- then from this sub list, the maximum version is kept

In your case, 2013-03-28 has been identified as a version object with the following properties:
- major: 2013
- minor: omitted thus 0
- patch: omitted thus 0
- qualifiers: ['03', '28']

**Comment by jschneider** [comment]
Thanks for the explanation.

In effect that means that it is impossible to ever do a downgrade. This might be problematic
in some cases.

Maybe a second mode can be useful for some people? Something like "use-nearest-tag"?
That should also solve a lot of performance issues and might work well for (very) large repositories?
I assume that had been the strategy up to 1.3?

**Comment by McFoggy** [comment]
> I assume that had been the strategy up to 1.3?

yes

**Comment by McFoggy** [comment]
please comment on jgitver/jgitver#70
