### ISSUE TITLE
Questions about eclipse integration / manifest manipulation

### ISSUE THREAD

**Issue by DrVanScott** [jgitver/jgitver-maven-plugin#112]
**version**:  1.4.5

**usage context**:

- [x] maven command line: 3.5.3  
- [x] eclipse: 2018-12 (4.10.0)

**Problem description**:

Please find a demo project here: https://github.com/DrVanScott/jgitverdemo

I am trying to manipulate the MANIFEST.MF. I need to store the project.version there.
Currently this is achived by maven-jar-plugin with a "archive" configuration. I understand, that this works only for the package phase.

    $ mvn package
    $ unzip -q -c target/jgitverdemo-0.0.0-SNAPSHOT.jar META-INF/MANIFEST.MF | grep Implementation-Version
    Implementation-Version: written by jar: 0.0.0-SNAPSHOT

works. The generated jar file contains a MANIFEST with the correct version retrieved by jgitver.
I also understand, that a 

    $ mvn compile
    $ cat target/classes/META-INF/MANIFEST.MF | grep Implementation-Version
    Implementation-Version: template

only copies the template manifest file. No modification is done.

If I "maven import" this project in eclipse and use eclipse mechanism to build the project (which i assume should be something like "mvn compile"), the manifest file under target/classes contains

    $ cat target/classes/META-INF/MANIFEST.MF | grep Implementation-Version
    Implementation-Version: written by jar: 0

(If you check the content of the file quite often during the build you can observe that first the template is copied, and finally replaced by the jar produced one.)

Why is eclipse extracting the jar into target/classes?
I would appreciate this behaviour, but unfortunately, jgitver is not part of the game. The plain version from the pom is used instead.

Without jgitver this behaviour was helpful: If we run our project within eclipse, the code was able to get the correct version (which currently is still stored directly in pom.xml) from the manifest: Eclipse stored it below target/classes/META-INF/MANIFEST.MF.

You can repeat above steps after uncommenting the maven-bundle-plugin. This time, "mvn compile" also leads to the correct value in the manifest. Still no luck with eclipse.

How to make eclipse considering jgitver-maven-plugin? Do you have any suggestions?

**Comment by McFoggy** [comment]
> Why is eclipse extracting the jar into target/classes?

it is not. It is just copying the resources to the target classes. As you have a template MANIFEST it first copy it.  
Then M2E (maven eclipse integration) enter the game and build the project but it looks like it is totally ignoring the jgitver extension.  
It seems to be a known issue : https://bugs.eclipse.org/bugs/show_bug.cgi?id=530587.

I also tried to use the template file and the filtering capabilities of maven

```
<build>
    <resources>
        <resource>
            <directory>src/main/resources</directory>
            <filtering>true</filtering>
        </resource>
    </resources>
...
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-jar-plugin</artifactId>
    <version>2.6</version>
    <configuration>
        <archive>
            <manifestFile>target/classes/META-INF/MANIFEST.MF</manifestFile>
           </archive>
    </configuration>
</plugin>
```

With MANIFEST being:

```
Manifest-Version: 1.0
Implementation-Version: ${jgitver.calculated_version}/${project.version}
```

but here again, m2e does not know anyhting about jgitver and thus the project version is still 0 and jgitver properties are unknown ; the result file after an eclipse build is

```
Manifest-Version: 1.0
Implementation-Version: ${jgitver.calculated_version}/0
Built-By: AWXGX
Build-Jdk: 1.8.0_191
Created-By: Maven Integration for Eclipse
```
whereas of course it works well using pure maven.

I do  not see other possibilities than not using build command but instead configure a build runner like the following
![image](https://user-images.githubusercontent.com/1119660/51076112-a7efeb00-1694-11e9-919a-60cd8997cdda.png)

Moreover it should be reported to eclipse m2e either by voting/commenting on the above issue or by creating a new one dedicated to jgitver.

**Comment by McFoggy** [comment]
@DrVanScott I have commented the eclispe m2e issue.

**Comment by DrVanScott** [comment]
@McFoggy Thank you very much for your detailed answer! I voted for the issue, let's hope there will be some progress... Anyway, this is just a small drawback compared to the cool things of jgitver! The issue won't stop us from using it. Thank you very much for this tool!

**Comment by McFoggy** [comment]
you're welcome.
