### ISSUE TITLE
Project module dependencies not resolved

### ISSUE THREAD

**Issue by fjakop** [jgitver/jgitver-maven-plugin#123]
**version**: 1.4.4

**usage context**:
- Intellij IDEA: 2019.2.4

**Problem description/reproduction**:

- Given two Maven projects A an B
- Project A has POM dependency to B (uses class of B)
- Dependency version NOT matching POM version but computed version (verified by mvn validate)
- Project B has jgitver version management
- Add both projects to IntelliJ project as Maven module
- Trigger a compile in IntelliJ

-> Result is project A not resolving project B's classes.

I've tried with and without `-Djgitver.skip=true` in IntelliJ's Maven settings.

**Comment by McFoggy** [comment]
First of all, Jetbrains has decided not to support dynamic versions from jgitver

* IDEA JIRA issue : https://youtrack.jetbrains.com/issue/IDEA-187928
* see topic discussed already https://github.com/jgitver/jgitver-maven-plugin/issues/81#issuecomment-541008148

This being said, you still have a possibility to do this:
- skip jgitver usage inside Intellij IDEA (or any other IDE)
- use a profile with specific dependency versions

You'll find an example in the sample [with-deps](https://github.com/jgitver/jgitver-samples/blob/master/with-deps/app/pom.xml) : there the profile was for Eclipse but it is more for a 'generic IDE'

As a resume today you have

## Initial

```
project B
version X computed as 1-snapshot
```

```
project A
version Y computed as whatever
dependencies
    dependency B 1-snapshot
```

## Changed to

the idea is to change project A to
```
project A
version Y computed as whatever
properties
    b.version 1-snapshot
dependencies
    dependency B ${b.version}
profiles
   profile IDE
      properties 
          property b.version X
```

If you import those 2 projects deactivatng jgitver and activating the IDE profile, then B version will be 
X and the dependency from A to B will also use X. Your IDE will match the 2 projects.
