### ISSUE TITLE
in maven mode allow SNAPSHOT on version tag 

### ISSUE THREAD

**Issue by McFoggy** [jgitver/jgitver-maven-plugin#132]
as requested in [#56 comments](https://github.com/jgitver/jgitver-maven-plugin/issues/56#issuecomment-635259062) we should provide a way to compute normal versions when `HEAD` is on a version tag commit.

That would mean, when HEAD (not detached) is on a commit A with tag vX.Y.Z 
* standard & default current behavior would lead to version computed: X.Y.Z
* by using some flag/config computation would lead to version computed: X.Y.(Z+1)-SNAPSHOT

**Comment by McFoggy** [comment]
@asyedin is it something like the above that you would like ?

**Comment by asyedin** [comment]
> @asyedin is it something like the above that you would like ?

@McFoggy - thank you so much, jgitver/jgitver#106 / jgitver/jgitver@348aa71 seems like exactly what I need. How can I test it with jgitver-maven-plugin?

**Comment by McFoggy** [comment]
I need to release jgitver & integrate the change in the plugin...

**Comment by danielebosetti** [comment]
Hi, this new feature would be useful for me too.
After building a release, we usually build and deploy the next snapshot version, and it would be nice if this worked even if no commits happened after the last release build.

**Comment by asyedin** [comment]
@McFoggy - any chance the new versions of jgitver and plugin could be released please?

**Comment by McFoggy** [comment]
`jgitver-0.13.0` is out ; I am releasing the associated `jgitver-maven-plugin`

you'll have to use `mvn -Djgitver.forceComputation=true` or environment property `jgitver.forceComputation` to `true` to activate the computation of the snapshot on a release tag, see below exemple. 
On the same commit using or not the forceComputation flag

![image](https://user-images.githubusercontent.com/1119660/100012096-03cc4480-2dd3-11eb-98ca-d036e80bffdd.png)

**Comment by McFoggy** [comment]
I'll look tomorrow at the build results ; travis seem to be down or totally crappy at the moment ; none of my builds are running https://travis-ci.org/github/jgitver/jgitver-maven-plugin/builds

**Comment by asyedin** [comment]
Awesome, thank you so much!

**Comment by McFoggy** [comment]
`jgitver-maven-plugin:1.6.0` is out.

There is potentially a regression regarding `dirty` state as I add to [bypass an it test](https://github.com/jgitver/jgitver-maven-plugin/commit/4fb439f9d6680b8e38424b6a3bf0c4cfd49a49b9).
I'll look at it later on and do a new release if required.
