### ISSUE TITLE
Why doesn't this plugin use jgit ?

### ISSUE THREAD

**Issue by msohn** [jgitver/jgitver-maven-plugin#135]
## Issue

We know that your time is precious, we are thankful that you take time to report us an issue, to make it easier for you please use the following prefilled paragraphs   

**version**:  any
**usage context**:

- [ ] maven command line: _replace with version_  
- [ ] eclipse: _replace with version_
- [ ] netbeans: _replace with version_
- [ ] Intellij IDEA: _replace with version_ 

**Problem description**:

This project is named jgitver-maven-plugin though it doesn't seem to use jgit (https://www.eclipse.org/jgit/).
Why are you then deriving your project's name from jgit ?
Please note the Eclipse trademark guidelines https://www.eclipse.org/legal/logo_guidelines.php.

**Comment by McFoggy** [comment]
Hi,

> This project is named jgitver-maven-plugin though it doesn't seem to use jgit

this project uses jgit under the hood via https://github.com/jgitver/jgitver.

> Why are you then deriving your project's name from jgit ?

I am not and it was never my goal. The name was build in shortening the concept of _git_ _versioning_. And then like many other projects, as it is a Java project, a _J_ was added. Thus the name `jgitver`.
