### ISSUE TITLE
Thinking about naming conventions: Maybe more Maven like?

### ISSUE THREAD

**Issue by jschneider** [jgitver/jgitver-maven-plugin#14]
In the sample in the documentation the lightweight is named "v1.1.0".
I have played around a bit and I will use tag names that end with "-SNAPSHOT" instead.
E.g.:  "1.1.0-SNAPSHOT"

I think this is more Maven-like and easier to explain.
No code changes are required. Only updates to the documentation.

**Comment by McFoggy** [comment]
I do not think such a change is required.
In JGitver, the lightweight tags are used to define a base version. This base version can contain a version and a serie of qualifiers. If we define a lightweight tag `v1.1.0-SNAPSHOT`, the base version will be:
- version 1.1.0
- qualifiers = ['SNAPSHOT']

This usage of qualifiers in base version is not necessary to be maven compliant when `jgitver` is used with the mode `mavenLike = true` which is the default of the jgitver-maven-plugin.

Instead, we can think about how to better explain the differences between the 2 actual existing version [stategies](https://github.com/jgitver/jgitver#configuration-modes--strategies).

**Comment by jschneider** [comment]
I am not saying that it is necessary. 
I just think that most developers that know Maven will understand "1.1.0-SNAPSHOT" intuitively.
