### ISSUE TITLE
jgitver interferes with spotbugs-maven-plugin

### ISSUE THREAD

**Issue by YaytayAtWork** [jgitver/jgitver-maven-plugin#145]
## Issue

**version**: 1.6.0

**usage context**:

- [ ] maven command line: 3.6.3
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: C:\Program Files\apache-maven-3.6.3\bin\..
Java version: 15, vendor: Azul Systems, Inc., runtime: C:\Program Files\Zulu\zulu-15
Default locale: en_GB, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
- [ ] netbeans: 12.1

**Problem description**:

This spotbugs configuration works without jgitver, but fails when jgitver is used.
```
      <plugin>
        <groupId>com.github.spotbugs</groupId>
        <artifactId>spotbugs-maven-plugin</artifactId>
        <version>4.1.4</version>
        <configuration>
          <fork>false</fork>
          <effort>Max</effort>
          <xmlOutput>true</xmlOutput>
          <excludeFilterFile>/findbugsFilterFile.xml</excludeFilterFile>
          <excludeFilterFile>/findbugsSecurityFilterFile.xml</excludeFilterFile>
          <onlyAnalyze>com.groupgti.shared.configservice.-</onlyAnalyze>
          <plugins>
            <plugin>
              <groupId>com.h3xstream.findsecbugs</groupId>
              <artifactId>findsecbugs-plugin</artifactId>
              <version>1.11.0</version>
            </plugin>
          </plugins>
        </configuration>
        <executions>
          <execution>
            <phase>verify</phase>
            <goals>
              <goal>check</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
```

The output ends with:
```
[INFO] >>> spotbugs-maven-plugin:4.1.4:check (default) > :spotbugs @ minimal-email-validator >>>
[INFO]
[INFO] --- spotbugs-maven-plugin:4.1.4:spotbugs (spotbugs) @ minimal-email-validator ---
[INFO] Fork Value is false
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:07 min
[INFO] Finished at: 2020-12-04T07:59:19Z
[INFO] ------------------------------------------------------------------------
[ERROR] Could not find resource '/findbugsSecurityFilterFile.xml'. -> [Help 1]
[ERROR]
```

Removing findsecbugs from the spotbugs configurations does not change the error.
Removing the <excludeFilterFile>/findbugsSecurityFilterFile.xml</excludeFilterFile> makes the error refer to findbugsFilterFile.xml.
Removing both excludeFileFile elements allows spotbugs to run (though obviously not with the config I want), and then I run into the same problem with checkstyle-plugin.

Changing the config to 
```
          <excludeFilterFile>${project.basedir}/findbugsFilterFile.xml</excludeFilterFile>
          <excludeFilterFile>${project.basedir}/findbugsSecurityFilterFile.xml</excludeFilterFile>
```
works.

It would be interesting to know why the config has to change, but as far as a fix is concerned I think this just needs adding to the issues in the readme.

**Comment by McFoggy** [comment]
The problem might come from the interpretation by spotbugs-maven-plugin of the path you specify in
`<excludeFilterFile>/findbugsFilterFile.xml</excludeFilterFile>`

This plugin might use the pom.xml file location to determine the base directory. If it is the case it is wrong, it should rely on the project basedir as you forced it to do in the later config.

I do not see this as a bug in jgitver.
