### ISSUE TITLE
Question regarding very simple configuration

### ISSUE THREAD

**Issue by pwittchen** [jgitver/jgitver-maven-plugin#150]
Hello,

First of all, thanks for your plugin!

I would like to achieve very simple thing using jgitver plugin. I would like to put the latest git tag **exactly as it is** into the project maven version in `pom.xml` file and when I'm building project from the develop branch, I just want to add `-SNAPSHOT` postfix to it.

For example:

I have tag: **v1.10.0-flink_1.11.2**

And now:
- When I build project while being checked out on the `master` branch, I would like to put this version to the `pom.xml` without any changes
- When I build project while being checked out on another branch (e.g. `develop`), I would like to put this version without any changes with just `-SNAPSHOT` postfix in the end

How can I achieve that?

I see different transformation options and other complicated stuff in the documentation, but I don't know how can I achieve this simple strategy with your plugin.

Without any configuration, plugin is doing weird things, e.g. creating versions like: **1.9.0-v1.10.0_flink_1.11.2-SNAPSHOT**, so it's merging latest tag with the previous tag and adding `-SNAPSHOT` prefix in the end, which is not desired behavior.

I'm looking forward to your help.

Regards,
Piotr

**Comment by McFoggy** [comment]
Hi Piotr,

without a reproducer, it is difficult to say why you have the behavior you describe.

But to answer your expectations, jgitver transform tags into a [semver](https://semver.org/) version.
So if you want to keep EXACTLY your tags, then I would say jgitver is not the tool you need. Perhaps look at the [maven ci friendly](https://maven.apache.org/maven-ci-friendly.html) pages.
From a CI (jenkins/gitlab/github/bamboo) it could answer better your need.

**Comment by pwittchen** [comment]
Ok, thanks.
