### ISSUE TITLE
Improved support for GitFlow like workflows: Differences between Branches

### ISSUE THREAD

**Issue by jschneider** [jgitver/jgitver-maven-plugin#16]
I am using GitFlow which is really, really great.

Development occurs in "develop". "master" always contains the latest, released version.

Example workflow can be seen in https://github.com/jschneider/jgitver-playing-ground

The version number calculation could be done like that:
in "master": 
- When a "real" git tag is set, use a release version (non snapshot)
- Ignore lightweight tags even on the same commit 

in "develop": 
- Always use a snapshot version
- if there is a tag at the current commit, increase the version number and convert to snapshot.

![GitFlow](http://nvie.com/img/git-model@2x.png)

**Comment by McFoggy** [comment]
marked as duplicate ; will have to be covered by jgitver/jgitver#15

**Comment by McFoggy** [comment]
have a look at ["branch_policy"](https://github.com/jgitver/jgitver-maven-plugin/tree/branch_policy) branch, I started to introduce a branch policy mechanism that should cover most of your needs. I'll add IT tests & documentation. You can also refer to the corresponding unit tests in [jgitver](https://github.com/jgitver/jgitver): [this one](https://github.com/jgitver/jgitver/blob/branch-policy/src/test/java/fr/brouillard/oss/jgitver/strategy/maven/others/Scenario13GitflowWithNonQualifierAndPartialNameTest.java) especially.

**Comment by mawl** [comment]
We are using git-flow in some projects in our company.

In git-flow, when I finish a release, the release branch is merged into master and tagged on the master branch:
![image](https://cloud.githubusercontent.com/assets/5493374/19182681/c8081982-8c74-11e6-9cee-cea884be5dd7.png)

I would have expected that the new development version on the develop branch then would be 2.0.1-SNAPSHOT but it's still 0.0.0-develop-SNAPSHOT.

**Comment by jschneider** [comment]
why did you not merge the tagged commit back into develop?
That should solve your issue in this case.

As you can see, the tagged commit is not a parent of the current develop HEAD

**Comment by McFoggy** [comment]
@mawl I agree with @jschneider, in your case if you merge back your tagged commit, you should have what you expect.

But I agree that we should perhaps plan/describe new schemes/behavior in order to support different workflows than the default ones.
Iin this area some help would be much appreciated in order to document the expected behaviors. The top would be some junit tests in a jgitver branch that could serve as documentation/discussion. Some  [draw.io](https://www.draw.io/) graphs could do the trick also.

**Comment by McFoggy** [comment]
in order to fully support other workflows dedicated issues could be opened.
