### ISSUE TITLE
Elegant way to convey Metadatas back to the environment

### ISSUE THREAD

**Issue by lbruun** [jgitver/jgitver-maven-plugin#163]
FEATURE REQUEST

In a CI pipeline it is crucial to be able to pick up the version which jgitver has applied to the project. (and possibly even other data from the jgitver Metadatas)

Currently this can be done like this:

```text
mvn  ${someMavenCommand} \
    com.github.ekryd.echo-maven-plugin:echo-maven-plugin:1.3.2:echo \
    -Decho.message="jgitver.used_version=\${jgitver.used_version}\${line.separator}jgitver.calculated_version=\${jgitver.calculated_version}\${line.separator}jgitver.dirty=\${jgitver.dirty}\${line.separator}jgitver.head_committer_name=\${jgitver.head_committer_name}\${line.separator}jgitver.head_commiter_email=\${jgitver.head_commiter_email}\${line.separator}jgitver.head_commit_datetime=\${jgitver.head_commit_datetime}\${line.separator}jgitver.git_sha1_full=\${jgitver.git_sha1_full}\${line.separator}jgitver.git_sha1_8=\${jgitver.git_sha1_8}\${line.separator}jgitver.branch_name=\${jgitver.branch_name}\${line.separator}jgitver.head_tags=\${jgitver.head_tags}\${line.separator}jgitver.head_annotated_tags=\${jgitver.head_annotated_tags}\${line.separator}jgitver.head_lightweight_tags=\${jgitver.head_lightweight_tags}\${line.separator}jgitver.base_tag=\${jgitver.base_tag}\${line.separator}"  \
    -Decho.toFile="jgitver.properties" 
```
When Maven has executed we now have a `jgitver.properties` file which we can read in the CI pipeline.

However, as can be seen above this is quite cumbersome: just look at the length of the line and the number of escapes.

Proposal: What if use of the Echo plugin wasn't needed in order to convey the jgitver Metadatas back to the surrounding environment?

Some ideas:

- jgitver-maven-plugin could set OS environment variables, one for each Metadatas property.
- jgitver-maven-plugin could itself automatically generate a `.properties` file (if you ask it to do so), either 
    - the name of the properties file could be specified in the config or via a System Property.
    - the name of the properties file could be determined by jgitver-maven-plugin (like a temp file) and then conveyed in an OS env var

**Comment by McFoggy** [comment]
why don't you add this to your pom? in a dedicated `ci` profile for example?

**Comment by lbruun** [comment]
Background: We've added jgitver (`jgitver-maven-plugin`) to the build pipeline of tons of projects more or less overnight. This has been done solely from the CI pipeline. The project's source repo is untouched. Meaning we have _not_ to each project committed a `.mvn/extensions.xml` and `.mvn/jgitver.config.xml` file.  Kind of like it this way. The whole jgitver thingy is a way to elegantly calculate a version string when artifacts are produced and this - in our world - only takes place from the CI system. There's basically no need to involve the Git repo - nor the individual developer - in this.

This is just to say that so far we've gotten away with not touching Git repos at all. It will be many, many repos we need to touch in order to do it via the POM.

**Comment by McFoggy** [comment]
Don't you have a company parent pom file neither ?

**Comment by lbruun** [comment]
@McFoggy. Not all inherit from the same company-wide POM. Even so, it will mean touching each individual Git repo in order to bump the version of the parent they use.

**Comment by McFoggy** [comment]
a `<exportProperties>PATH_TO_FILE</exportProperties>` config property can be added to `.mvn/jgitver.config.xml`

**Comment by lbruun** [comment]
> 
> 
> a `<exportProperties>PATH_TO_FILE</exportProperties>` config property can be added to `.mvn/jgitver.config.xml`

Yes, that would be a good solution.
