### ISSUE TITLE
Building within Github Actions always results in snapshot

### ISSUE THREAD

**Issue by alibabashack** [jgitver/jgitver-maven-plugin#169]
## Issue

**version**: 1.8.0 (from maven central) 

**usage context**:

- [x] maven command line: 3.8.? (Github actions default) and 3.6.3 (Ubuntu 20.04) 
- [x] eclipse: none
- [x] netbeans: none
- [x] Intellij IDEA: none
- [x] NO config file (defaults apply - > maven versionig scheme) 
- [x] checkout is performed with tag fetch, so all tags and branches are available to jgitver

**Problem description**:

When building from an annotated git tag (detached head) within github actions CI, this always results in a - SNAPSHOT suffix version for me. The version number is picked up correctly from the tag. However, I expect a release version without SNAPSHOT.

For example see the following actions run:
https://github.com/alibabashack/rxtx/runs/4606812319?check_suite_focus=true

In bullet 

- _run actions/checkout@v2_
  - _fetching the repository_: Note all tags and branches are fetched and are visible (especially tag _2.4_)
  - _checking out the ref_: Note tag _2.4_ is checked out in detached head state
- _Bundle rxtx Java native libs_: 2.4.0-SNAPSHOT is calculated from the tag.
- _Release_: Note version 2.4.0-SNAPSHOT is created from tag _2.4_.

I expect version 2.4.0 instead of 2.4.0-SNAPSHOT.

When the version is calculated based on the same repository on my local ubuntu 20.04 machine (also in detached head state on the same tag) no SNAPSHOT suffix is added.

I do not see any configuration differences between the github action run and my local run. Still it results in two different outcomes. Any ideas? 

Thanks a lot for this project. It is a huge help in order to DRY in the insane maven world.

**Comment by alibabashack** [comment]
I think I accidentally did not use an annotated tag. I will inveatigate first.

**Comment by alibabashack** [comment]
Ok, I really used an annotated tag. I was confused by the git options, but option -m implies -a, so this does not seem to be the issue here.

**Comment by alibabashack** [comment]
I found the problem: A misconfiguration of my github workflow. If your workflow is distributed across multiple build host, all of them have to checkout the repository with a fetch-depth of 0, of course. :)

**Comment by McFoggy** [comment]
Fine that you found your issue.
It's the same with other CI (Jenkins for example) if you build on different nodes you have to checkout on all of them.
