### ISSUE TITLE
Suspicious 1.9.0 version appeared on maven central

### ISSUE THREAD

**Issue by dade-hms** [jgitver/jgitver-maven-plugin#170]
## Issue

**version**: 1.9.0

**usage context**:

irrelevant

**Problem description**:

Maven central expose a version 1.9.0 of jgitver maven plugin. The tag list in this github show only tags up to 1.8.0.  Either it is a rogue version on maven central or this github lack the proper tag to know which code was released to central.

Could you confirm it's an official version?

**Comment by McFoggy** [comment]
sorry it is official, I forgot to push the tag.
