### ISSUE TITLE
Multi module project: Can not resolve versions for test-jar deps

### ISSUE THREAD

**Issue by jschneider** [jgitver/jgitver-maven-plugin#20]
I have a multi module project. Building it from the main directory works.

I have two problems:
- I have defined a dependency to another module with version "${project.version}". This works usually. But if the type is "test-jar", Maven tries to download the version "0".

Sample:
Multi-Module pom.xml:

```
<groupId>my.group</groupId>
<artifactId>parent</artifactId>

<dependencyManagement>
<dependencies>
      <dependency>
        <groupId>my.group</groupId>
        <artifactId>domain</artifactId>
        <version>${project.version}</version>
        <type>test-jar</type>
        <scope>test</scope>
      </dependency>
```

Child pom.xml:

```
<groupId>my.group</groupId>
<artifactId>ui</artifactId>

<dependencies>
<dependency>
      <groupId>my.group</groupId>
      <artifactId>domain</artifactId>
      <type>test-jar</type>
    </dependency>

```

**Comment by McFoggy** [comment]
this issue should now be corrected with the 0.3.0-alpha2 release.
Please review the README to use the new maven core extension mechnism.
