### ISSUE TITLE
Version-Number modified problem with nexus-staging-maven-plugin

### ISSUE THREAD

**Issue by jschneider** [jgitver/jgitver-maven-plugin#33]
Using version 0.3.0-alpha2.

Building as free style project in Jenkins fails with this message:

The project com.cedarsoft:open:75.1.1-SNAPSHOT (/var/lib/jenkins/jobs/com.cedarsoft.open/workspace/pom.xml) has 1 error
[ERROR]     Unresolveable build extension: Plugin org.sonatype.plugins:nexus-staging-maven-plugin:1.6.7 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.sonatype.plugins:nexus-staging-maven-plugin:jar:1.6.7: Could not find artifact org.sonatype.nexus.maven:nexus-staging:pom:75.1.1-SNAPSHOT in sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots/) -> [Help 2]
org.apache.maven.plugin.PluginManagerException: Plugin org.sonatype.plugins:nexus-staging-maven-plugin:1.6.7 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.sonatype.plugins:nexus-staging-maven-plugin:jar:1.6.7

It seems to be a bit strange. But obviously the version number for the parent of an other extension is set to a invalid value.

This problem does not happen when executed as stand alone. So probably it is a Jenkins bug... Buy maybe you have an idea?

**Comment by McFoggy** [comment]
can be that you are facing https://issues.jenkins-ci.org/browse/JENKINS-30058.

How is your jenkins configured?
In your free style are you using:
- maven integration "invoke maven top level goal"
- shell/batch commands
- pipeline DSL

do you face the issue with: https://github.com/jschneider/com.cedarsoft.open/tree/develop ?

**Comment by jschneider** [comment]
Correction: It does also happen when executed on the command line.
But it works on my machine....

I'll try to figure it out.

**Comment by jschneider** [comment]
And yes: The problem happens with: https://github.com/jschneider/com.cedarsoft.open/tree/develop

**Comment by McFoggy** [comment]
also 36d5036 can improve that.
I have just release `0.3.0-alpha4` that includes it, can you retest?

**Comment by McFoggy** [comment]
please also describe the full jenkins setup, especially regarding maven  configuration:
- built-in (which version)
- standalone installation (which version)
- ...

**Comment by jschneider** [comment]
Ok, found out more:

If the Maven repo is set to "$WORKSPACE/.repository" it fails. 
If it is set to another directory, it works. Very strange.

It definitely is unrelated to Jenkins. It is reproducible on the command line.

**Comment by jschneider** [comment]
Just give it a shot:
mvn validate -Dmaven.repo.local=.repository

**Comment by McFoggy** [comment]
> If the Maven repo is set to "$WORKSPACE/.repository" it fails.

I might know where it comes from then if I suppose that your project is checkout in `$WORKSPACE` and then that you end up with:
- $WORKSPACE/pom.xml
- $WORKSPACE/.mvn
- $WORKSPACE/.repository

If you are in such a situation, then you are facing quite the same situation than some of the IT tests inside the jgitver-maven-plugin are facing: jgitver-maven-plugin extension is in action where it should not. This is due to the fact that parent directory of the pom contains the .mvn that activates the jgitver extension. 
In your case, the only workaround for now is to set the local repo elsewhere.

**Comment by McFoggy** [comment]
I think I could workaround that by adding some exclusion patterns in the configuration.

**Comment by jschneider** [comment]
Yes. You are right.

$WORKSPACE/pom.xml
$WORKSPACE/.mvn
$WORKSPACE/.repository: set as local repository location

**Comment by McFoggy** [comment]
using my latest changes

![image](https://cloud.githubusercontent.com/assets/1119660/17417751/3d0299ea-5a95-11e6-920b-c8ffdbd98d28.png)

with `jgitver.config.xml`

```
<configuration>
  <mavenLike>true</mavenLike>
  <nonQualifierBranches>master,develop</nonQualifierBranches>
  <exclusions>
    <exclusion>.repository</exclusion>
  </exclusions>
</configuration>
```

**Comment by jschneider** [comment]
Great. Thanks.
Looking forward to the next release

**Comment by McFoggy** [comment]
@jschneider version `0.3.0` has been published to sonatype, it's on its road to central (will be there on next sync between the 2 repos).
