### ISSUE TITLE
Configuration option 'useDirty' doesn't make any effect.

### ISSUE THREAD

**Issue by xeagle2** [jgitver/jgitver-maven-plugin#36]
**extensions.xml**

```
<extensions xmlns="http://maven.apache.org/EXTENSIONS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://maven.apache.org/EXTENSIONS/1.0.0 http://maven.apache.org/xsd/core-extensions-1.0.0.xsd">
    <extension>
        <groupId>fr.brouillard.oss</groupId>
        <artifactId>jgitver-maven-plugin</artifactId>
        <version>0.3.0</version>
    </extension>
</extensions>
```

**jgitver.config.xml**

```
<configuration>
    <mavenLike>true</mavenLike>
    <useDirty>false</useDirty>
</configuration>
```

The calculated version doesn't contain the 'dirty' as qualifier.

**Comment by McFoggy** [comment]
the parameter is not used by [jgitver](https://github.com/jgitver/jgitver) `fr.brouillard.oss.jgitver.impl.MavenVersionStrategy`

**Comment by McFoggy** [comment]
auto-building jgitver-maven-plugin with jgitver:jgitver:0.2.1-SNAPSHOT`and activating dirty use in`jgitver.config.xml`

```
<configuration>
    <useDirty>true</useDirty>
    ...
</configuration>
```

results correctly in having the dirty qualifier being added (because of uncommited files).
![image](https://cloud.githubusercontent.com/assets/1119660/18207488/a3faa262-712b-11e6-8d7d-6e102f848986.png)

I'll close the issue when a new release of jgitver will be available.

**Comment by xeagle2** [comment]
Is there any reason fr.brouillard.oss.jgitver.impl.MavenVersionStrategy doesn't handle this parameter? I guess it makes sense to handle it. It doesn't violate the maven versioning semantics using the qualifier which could have SNAPSHOT or SNAPSHOT-dirty, or just 1.1.1-dirty.

'Dirty' flag is useful and I honestly believe there is a gap that strategy ignores it, don't you think this?

**Comment by McFoggy** [comment]
No there's no reason... That's why I implemented it, see above.
You'll have to wait for a release of `jgitver > 0.2.0` including jgitver/jgitver#18

**Comment by xeagle2** [comment]
Ah, sorry was a bit confused, it sounds good, will be looking forward to try next release! :)
