### ISSUE TITLE
It would be helpful to have .xsd for jgitver.config.xml

### ISSUE THREAD

**Issue by xeagle2** [jgitver/jgitver-maven-plugin#37]
In most cases it's easy to make the mistakes while specifying the configuration in jgitver.config.xml. 

It would be helpful to have at least .xsd to help others configure the plugin properly from IDEs and it would be a good step ahead to validate configuration while it's loaded by plugin.

Would be nice to have this feature.

Thank you,

**Comment by McFoggy** [comment]
Here is my WIP in branch [issue-37](https://github.com/jgitver/jgitver-maven-plugin/tree/issue-37) regarding this issue
- [x] create initial xml-schema file
- [x] publish xsd: https://jgitver.github.io/maven/configuration/jgitver-configuration-v1_0_0-beta.xsd
- [x] document usage
- [x] add tests
