### ISSUE TITLE
nonQualifierBranches: Support for wild cards

### ISSUE THREAD

**Issue by jschneider** [jgitver/jgitver-maven-plugin#38]
I would like to deploy (mvn deploy -DperformRelease) from a release branch that has a name like "release/1.2.3".
This results in a version number like "1.2.3-release" - which oviously is not what I want.

Therefore I'd like to set "nonQualifierBranches" to something like "release/*"

**Comment by McFoggy** [comment]
it should be possible with the usage of `branchPolicy`

```
    <branchPolicies>
        <branchPolicy>
            <pattern>release.*</pattern>                  <!-- regex pattern -->
            <transformations>                           
                <transformation>IGNORE</transformation>
            </transformations>
        </branchPolicy>
```

`
I give you that untested and just by heart/looking at doc/readme ; I'll do a full test in few hours when back to home and will come back to you.

**Comment by jschneider** [comment]
Oh great. Thanks. I will give it a shot.

**Comment by McFoggy** [comment]
I successfully tested correctly using the following syntax (take care of the parenthesis as capturing group):

```
<branchPolicies>
    <branchPolicy>
        <pattern>(release.*)</pattern>                  <!-- regex pattern -->
        <transformations>                           
            <transformation>IGNORE</transformation>
        </transformations>
    </branchPolicy>
</branchPolicies>
```

take care that setting manual branching policy, makes _nonQualifierBranches_ option obsolete ; ie not used.
If you want to also skip `master` as being a qualifier, then add another branch policy in the configuration.

**Comment by jschneider** [comment]
Yes. Works like a charm. Missed that one in the documentation.

Thanks for pointing that out.
