### ISSUE TITLE
Configuration#nonQualifierBranches should support a list (multiple xml entries)

### ISSUE THREAD

**Issue by jschneider** [jgitver/jgitver-maven-plugin#39]
Like in fr.brouillard.oss.jgitver.JGitverPluginConfiguration#nonQualifierBranches

**Comment by McFoggy** [comment]
as described in README it supports a list of comma separated branch name ; isn't that enough?

For complicated use cases, the idea was to use the branchPolicies.

**Comment by jschneider** [comment]
Yes. branch policies is what solves this. Thanks.

**Comment by McFoggy** [comment]
glad to hear it covered your needs.
