### ISSUE TITLE
Document continuous delivery process

### ISSUE THREAD

**Issue by vromero** [jgitver/jgitver-maven-plugin#46]
### Before submitting an issue I have first:

- [x] searched for similar already existing issue
- [x] read the documentation and [wiki](https://github.com/jgitver/jgitver-maven-plugin/wiki) 

*(if you have performed all the above, remove the paragraph and continue describing the issue with template below)*

## Issue

As a user I would like to be able to follow a prescriptive guide to have a continuous delivery pipeline.
Related with https://github.com/jgitver/jgitver/issues/21.

**Comment by McFoggy** [comment]
I fully agree that it is required.

it relates also to #43, #45 and more generally to some user guides addressing possible uses cases.

**Comment by McFoggy** [comment]
@vromero I started to document deployments in the wiki https://github.com/jgitver/jgitver-maven-plugin/wiki/continuous-deployment---semi-automated. Could you give some feedback?

**Comment by vromero** [comment]
Excellent, thanks!
Will review later today.

**Comment by vromero** [comment]
Oh! I completely forgot about this. Thanks a lot (and thanks for the software), looks great.
