### ISSUE TITLE
Problems when releasing: Invalid signature

### ISSUE THREAD

**Issue by jschneider** [jgitver/jgitver-maven-plugin#49]
I have this problem with different projects.
Latest case: https://github.com/jschneider/com.cedarsoft.commons/releases/tag/7.4.0

I try to deploy to oss.sonatype.org but run into an "Invalid Signature" with my pom/pom.asc
What I could find out so far:

* I am doing a "mvn clean deploy -DperformRelease"
* target/commons-7.4.0.pom is the same as "pom.xml" (contains "0" as version number)
* the signature in target/commons-7.4.0.pom is valid
* the pom in "target/nexus-staging/staging/3755bb868da9a4/com/cedarsoft/commons/7.4.0" looks different. The version number has changed and some other changes can be found (new lines removed, changed order of scm tag)

So my guess is:
* jgitver modifiers the pom.xml (adds the version number)
  * (why are other things than the version number changed?)
* the original pom.xml is signed (with "0" as version number) and copied to target (why?)
* the changed pom.xml is staged for deployment - but with the old signature

I have a single module project - there everything seems to work fine. I have taken a look into "target". There is the modified version of the pom.xml...

So I think the question is: Why does the unmodified pom.xml end up in the target dir?
I think this might be the root problem.

**Comment by jschneider** [comment]
I am creating a minimal sample project:

https://github.com/jschneider/com.cedarsoft.jgitver-deployment-problem

**Comment by jschneider** [comment]
I am trying and trying. The only thing I found out: My example fails as soon as I add a parent.
When adding the content of the parent directly into my pom, everything seems to work just fine...

**Comment by jschneider** [comment]
Ok, I am not sure what I have found out.
But at the moment the project is failing every time with:

Invalid Signature: '/com/cedarsoft/jgitver-deployment-problem/0.2.6/jgitver-deployment-problem-0.2.3.pom.asc' is not a valid signature for 'jgitver-deployment-problem-0.2.6.pom'.


The (so far) simplest version:
https://github.com/jschneider/com.cedarsoft.jgitver-deployment-problem/releases/tag/0.2.6

**Comment by jschneider** [comment]
I have created an issue for nexus-staging-plugin:
https://issues.sonatype.org/browse/NEXUS-12437

**Comment by jschneider** [comment]
Ok, I think the problem is very clear:
The gpg-plugin signs the original pom.xml and not the one created by jgitver (in /tmp).
Therefore the signature is not valid.

I think that might be a problem with the gpg-plugin?

**Comment by jschneider** [comment]
But since you are able to relase jgitver *with* nexus-staging and valid signatures.... Any idea how you do this?

**Comment by jschneider** [comment]
Some new information:

The gpg plugin loads the pom using "project.getFile()"
This returns "/home/johannes/projects/com.cedarsoft.jgitver-deployment-problem/pom.xml" for my sample project.
The output tells me that jgitver is active.


Coming closer: Obviously the order the plugins are running in, is relevant. In my project the gpg-plugin runs *before* 
jgitver-maven-plugin:0.4.0:attach-modified-poms 


Both plugins run in the "verify" phase.

**Comment by jschneider** [comment]
https://github.com/jgitver/jgitver-maven-plugin/issues/50

**Comment by McFoggy** [comment]
sorry for the non answers/feedback in this thread ; I wasn't available during the week-end.
