### ISSUE TITLE
Run "attach-modified-poms" earlier

### ISSUE THREAD

**Issue by jschneider** [jgitver/jgitver-maven-plugin#50]
I run into the problem that the gpg-plugin run *before* "attach-modified-poms".
That leads to invalid signatures since the gpg-plugin signs the original pom.xml

I'd suggest to run "attach-modified-poms" as early as possible. There might be other plugins in other phases that could run into the same issue.

**Comment by McFoggy** [comment]
@jschneider thanks for reporting this, as you mentioned in #49 I use also the gpg plugin but never came to the same issue.  
I suggest that we try to run "attach-modified-poms" during the "prepare-package" phase.
Would it be ok?

**Comment by McFoggy** [comment]
thinking a bit more on it, perhaps we should even go further and modify the pom as early as possible in the build process, perhaps by running it as first plugin during "initialize" or even "verify" phase.

**Comment by jschneider** [comment]
I think as early as possible sounds good. I don't see a reason not to update the pom asap.

Maybe we should try with some other plugins. I think the jar-plugin might add the pom.xml to the jar in some configurations?
