### ISSUE TITLE
Plugin is incompatible with Artifactory Jenkins Plugin

### ISSUE THREAD

**Issue by gimmebytes** [jgitver/jgitver-maven-plugin#55]
## Issue

First off: Nice plugin, good idea and clean approach to automatically generate version numbers based on the git history. Unfortunately it seems that the plugin is not compatible with the Artifactory Plugin of Jenkins inside our CI environment. I will describe the details below.  

**version**: 0.4.0

**usage context**:
- [ X ] maven command line: 3.3.9 and 3.3.3
- [ X ] Intellij IDEA: 2016.3
- [ X ] Jenkins: 2.49
- [ X ] Artifactory Plugin for Jenkins 2.10.1 https://wiki.jenkins-ci.org/display/JENKINS/Artifactory+Plugin

**Problem description**:

I'm currently working on a new internally used set of libraries composed as multi module project using maven. I've added the plugin as described (.mvn/extension.xml). Locally it's working totally fine using intelliJ. But inside Jenkins the plugin breaks the Artifactory Plugin to publish the generated artifacts to a artifactory server instance.

I'm using a JenkinsFile to build the artifacts - snip

```
checkout(...)
def server = Artifactory.server 'maven'
def buildInfo = Artifactory.newBuildInfo()
buildInfo.env.capture = true
def rtMaven = Artifactory.newMavenBuild()
rtMaven.tool = 'MavenLatest'
rtMaven.deployer releaseRepo:'java-releases', snapshotRepo:'java-snapshots', server: server
rtMaven.deployer.artifactDeploymentPatterns.addInclude('....)
rtMaven.run pom: 'pom.xml', goals: 'clean package', buildInfo: buildInfo
server.publishBuildInfo buildInfo}
```

The Artifactory Plugin is calling maven internally, which is working fine and the jgtiver plugin is also invoked with no issues:

`java -classpath /opt/maven/apache-maven-3.3.9/boot/plexus-classworlds-2.5.2.jar -Dmaven.home=/opt/maven/apache-maven-3.3.9 -DbuildInfoConfig.propertiesFile=/tmp/buildInfo5131567399890492507.properties -Dclassworlds.conf=/tmp/classworlds9114561323625377013conf -Dmaven.multiModuleProjectDirectory=/var/lib/jenkins/path-to-project -org.codehaus.plexus.classworlds.launcher.Launcher -f pom.xml clean package`

Output (I've omitted some names for privacy reasons):

`[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - Scanning for projects...
[main] INFO fr.brouillard.oss.jgitver.JGitverModelProcessor - jgitver-maven-plugin is about to change project(s) version(s)
[main] INFO fr.brouillard.oss.jgitver.JGitverExtension -     XXX::XXX-YYY:1.0.0-SNAPSHOT -> 1.0.0-SNAPSHOT
....
[main] INFO org.jfrog.build.extractor.maven.BuildInfoRecorder - Initializing Artifactory Build-Info Recording
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - ------------------------------------------------------------------------
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - Reactor Build Order:
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - 
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - XXX-YYY
...
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger -                                                                         
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - ------------------------------------------------------------------------
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - Building XXX-YYY 1.0.0-SNAPSHOT
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - ---------------------------------------------------------`

But then the Artifactory Plugin kicks in and hangs:

`[main] ERROR org.jfrog.build.extractor.maven.resolver.ArtifactoryEclipseRepositoryListener - Failed while enforcing Artifactory artifact resolver
org.codehaus.plexus.component.repository.exception.ComponentLookupException: java.util.NoSuchElementException
      role: org.jfrog.build.extractor.maven.resolver.ArtifactoryEclipseArtifactResolver
  roleHint: 
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:267)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:243)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:237)
	at `

I saw that your plugin is using plexus as well - Is it possible, that the plugin overrides the plexus context and therefore the Artifactory Plugin is unable to find their registered components?

I would really like to use your plugin in production, but on the other hand I'm not able to dismiss artifactory as of now.

If you need further information let me know.

Best regards,
Marvin K.
Statista

PS: Sorry for the bad JenkinsFile formatting, my Markdown skills are kinda bad.

**Comment by McFoggy** [comment]
@gimmebytes would you be able to create a simple maven repoducer case that I could use to test & use to reproduce the problem on a fresh new local artifactory installation. I guess the problem is more related to artifactory maven plugin itself than to your maven multi-module project, so a reproducer could probably be  created.

**Comment by McFoggy** [comment]
@gimmebytes sorry but it looks like artifactory jenkins plugin does not install itself correctly. I tried with a local fresh `jenkins-2.19.2` & `jenkins-2.46.1`. Both installations ended with the following artifactory errors ; sadly I cannot investigate your issue further.

If you find a way to have a local jenkins installation with the artifactory plugin, ping me for instructions.

```
←[0m←[33mavr. 04, 2017 7:48:08 PM hudson.ExtensionFinder$GuiceFinder$FaultTolerantScope$1 error
AVERTISSEMENT: Failed to instantiate Key[type=org.jfrog.hudson.ArtifactoryBuilder$DescriptorImpl, annotation=[none]]; skipping this component
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, java.lang.NullPointerException
  at org.jfrog.hudson.ArtifactoryBuilder$DescriptorImpl.<init>(ArtifactoryBuilder.java:78)

1 error
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:52)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
        at hudson.ExtensionFinder$GuiceFinder$FaultTolerantScope$1.get(ExtensionFinder.java:424)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
        at hudson.ExtensionFinder$GuiceFinder._find(ExtensionFinder.java:386)
        at hudson.ExtensionFinder$GuiceFinder.access$000(ExtensionFinder.java:232)
        at hudson.ExtensionFinder$GuiceFinder$3.find(ExtensionFinder.java:341)
        at jenkins.ExtensionComponentSet$3.find(ExtensionComponentSet.java:98)
        at jenkins.ExtensionComponentSet$1.find(ExtensionComponentSet.java:70)
        at hudson.DescriptorExtensionList.load(DescriptorExtensionList.java:196)
        at hudson.ExtensionList.refresh(ExtensionList.java:328)
        at jenkins.model.Jenkins.refreshExtensions(Jenkins.java:2649)
        at hudson.PluginManager.dynamicLoad(PluginManager.java:868)
        at hudson.PluginManager.dynamicLoad(PluginManager.java:814)
        at hudson.model.UpdateCenter$InstallationJob._run(UpdateCenter.java:1891)
        at hudson.model.UpdateCenter$DownloadJob.run(UpdateCenter.java:1652)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at hudson.remoting.AtmostOneThreadExecutor$Worker.run(AtmostOneThreadExecutor.java:110)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at org.jfrog.hudson.ArtifactoryBuilder$DescriptorImpl.setConnectionRetry(ArtifactoryBuilder.java:90)
        at org.jfrog.hudson.ArtifactoryBuilder$DescriptorImpl.<init>(ArtifactoryBuilder.java:81)
        at org.jfrog.hudson.ArtifactoryBuilder$DescriptorImpl$$FastClassByGuice$$f4c7f293.newInstance(<generated>)
        at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40)
        at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:61)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:105)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        ... 22 more
```

**Comment by gimmebytes** [comment]
@McFoggy

Sure, I will try to Provide a simple example for you so that you can try to reproduce. I have the feeling that on a plain Installation everything will work, but lets see :-)

**Comment by McFoggy** [comment]
@gimmebytes could you installed correctly the Artifactory plugin in a fresh new jenkins? I would like to help here but I am stuck without environment.

**Comment by gimmebytes** [comment]
@McFoggy

I'm sorry that I didn't reply earlier. I've tried to reach you out via mail end of April, but that mail couldn't be delivered some how. My family encountered a personal loss in April and I wasn't a lot in the office. But still I want to provide a working example for you to make this thing work.

Will get back to you asap.

Best regards

**Comment by gimmebytes** [comment]
Today I took the time to setup a new Jenkins Server to try to reproduce the issue on a blank machine. In the end the same error as mentioned above occurred. 

As work around I am now using the maven deploy plugin to deploy the artifacts to our Artifactory server which is working totally fine. I can provide further details if you're interested. 

Find the steps to setup a blank jenkins machine below:

1) Installed ubuntu 16.04 LTS (server edition) - installed using virtualbox, selected nothing special during installation (openSSH server)
2) Installed jre from oracle
https://www.digitalocean.com/community/tutorials/how-to-install-java-with-apt-get-on-ubuntu-16-04
3) Installed Jenkins 2.46 from official repository
https://pkg.jenkins.io/debian-stable/
4) Fired up Jenkins and installed suggested plugins
5) Created default user
6) Install maven 3 via apt-get (version 3.3.9) and configure inside jenkins (global tool configuration, setting home to /usr/share/maven)
7) Install artifactory plugin and configured it accordingly to our server (2.11.0)
8) Added mvn extension (jgitver) to project
9) Adjusted version number layout so that jgitver works fine locally
10) Created Jenkins job and tried to build and deploy

**Comment by McFoggy** [comment]
@gimmebytes Glad that you find a usable workaround for your installation.

**Comment by dbcall2** [comment]
I'm having the same issue as @gimmebytes above... When the artifactory plugin fires up it is able to resolve the plugin artifacts just fine. Once jgitver is invoked the artifactory plugin can no longer find it's artifact resolver. @McFoggy Would you please reopen this issue until the root cause can be determined? This plugin is exactly what we need but it has to play nice with Artifactory for it to be fully useful. 

I'm happy to contribute code changes once I fully understand the root of the issue. It is currently unclear how this initial call succeeds: 
<pre>[main] DEBUG org.eclipse.aether.internal.impl.DefaultLocalRepositoryProvider - Using manager EnhancedLocalRepositoryManager with priority 10.0 for /home/ciuser/.m2/repository
[main] DEBUG org.jfrog.build.extractor.maven.resolver.ArtifactoryEclipseRepositoryListener - Enforcing Artifactory artifact resolver
[main] DEBUG org.jfrog.build.extractor.maven.resolver.ArtifactoryEclipseRepositoryListener - [buildinfo] Resolved artifact: fr.brouillard.oss:jgitver-maven-plugin:pom:1.4.4:build from: te2-all (http://localhost:8081/artifactory/te2-all, default, releases) Context is: plugin
[main] DEBUG org.eclipse.aether.internal.impl.DefaultRemoteRepositoryManager - Using mirror te2-all (http://localhost:8081/artifactory/te2-all) for central </pre>

but this one fails:

<pre>[main] DEBUG org.jfrog.build.extractor.maven.resolver.ArtifactoryEclipseRepositoryListener - Enforcing Artifactory artifact resolver
[main] ERROR org.jfrog.build.extractor.maven.resolver.ArtifactoryEclipseRepositoryListener - Failed while enforcing Artifactory artifact resolver
org.codehaus.plexus.component.repository.exception.ComponentLookupException: java.util.NoSuchElementException
      role: org.jfrog.build.extractor.maven.resolver.ArtifactoryEclipseArtifactResolver
  roleHint: 
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:267)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:243)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:237)
	at org.jfrog.build.extractor.maven.resolver.ArtifactoryEclipseRepositoryListener.enforceArtifactory</pre>

Once the jgitver extension is invoked the Artifactory plugin can no longer look up its dependencies.

**Comment by McFoggy** [comment]
what is the type of job you use in Jenkins?

**Comment by dbcall2** [comment]
We're currently using a scripted pipeline job (Jenkinsfile w/shared lib).

**Comment by McFoggy** [comment]
using following docker-compose file, I am trying to reproduce

```
version: '3'
services:
  artifactory:
    image: "docker.bintray.io/jfrog/artifactory-oss:6.5.13"
    ports: 
      - "8090:8081"
  jenkins:
    image: "jenkins/jenkins:2.156"
    ports:
      - "8080:8080"
      - "50000:50000"
```

first thing I have noticed is that installation of artifactory plugin also installed a jenkins plugin called "Maven integration"

![image](https://user-images.githubusercontent.com/1119660/50102860-81ba6500-0226-11e9-9656-8a4a8f71dbba.png)

more to come...

**Comment by McFoggy** [comment]
I finally succeed in setup artifactory and defined a maven job in jenkins that publishes to artifactory.

I did not receive any error but jgitver was not involved when using the maven job type ; which is not new for me.

```
Building in workspace /var/jenkins_home/workspace/jgitver-maven-job-with-artifactory
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/jgitver/jgitver.git # timeout=10
Fetching upstream changes from https://github.com/jgitver/jgitver.git
 > git --version # timeout=10
 > git fetch --tags --progress https://github.com/jgitver/jgitver.git +refs/heads/*:refs/remotes/origin/*
 > git rev-parse refs/remotes/origin/master^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/master^{commit} # timeout=10
Checking out Revision d50d2d8dafabd5497cfd019136e02eb441c438b4 (refs/remotes/origin/master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f d50d2d8dafabd5497cfd019136e02eb441c438b4
Commit message: "use jgitver-maven-plugin 1.4.4"
 > git rev-list --no-walk d50d2d8dafabd5497cfd019136e02eb441c438b4 # timeout=10
Parsing POMs
Established TCP socket on 33177
[jgitver-maven-job-with-artifactory] $ /usr/lib/jvm/java-8-openjdk-amd64/bin/java -cp /var/jenkins_home/plugins/maven-plugin/WEB-INF/lib/maven33-agent-1.12.jar:/var/jenkins_home/tools/hudson.tasks.Maven_MavenInstallation/mvn-3.3.9/boot/plexus-classworlds-2.5.2.jar:/var/jenkins_home/tools/hudson.tasks.Maven_MavenInstallation/mvn-3.3.9/conf/logging jenkins.maven3.agent.Maven33Main /var/jenkins_home/tools/hudson.tasks.Maven_MavenInstallation/mvn-3.3.9 /var/jenkins_home/war/WEB-INF/lib/remoting-3.28.jar /var/jenkins_home/plugins/maven-plugin/WEB-INF/lib/maven33-interceptor-1.12.jar /var/jenkins_home/plugins/maven-plugin/WEB-INF/lib/maven3-interceptor-commons-1.12.jar 33177
<===[JENKINS REMOTING CAPACITY]===>channel started
Executing Maven:  -B -f /var/jenkins_home/workspace/jgitver-maven-job-with-artifactory/pom.xml install -DskipTests=true
[INFO] Scanning for projects...
[INFO] Initializing Artifactory Build-Info Recording
[HUDSON] Collecting dependencies info
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building GIT versioning using jgit 0
[INFO] ------------------------------------------------------------------------
...

...
[INFO] Artifactory Build Info Recorder: Saving Build Info to '/var/jenkins_home/workspace/jgitver-maven-job-with-artifactory/target/build-info.json'
[INFO] Deploying artifact: http://artifactory:8081/artifactory/libs-release-local/fr/brouillard/oss/jgitver/0/jgitver-0.jar
[INFO] Deploying artifact: http://artifactory:8081/artifactory/libs-release-local/fr/brouillard/oss/jgitver/0/jgitver-0.pom
[INFO] Artifactory Build Info Recorder: Deploying build info ...
[INFO] Deploying build descriptor to: http://artifactory:8081/artifactory/api/build
[INFO] Build successfully deployed. Browse it in Artifactory under http://artifactory:8081/artifactory/webapp/builds/jgitver-maven-job-with-artifactory/2
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 15.477 s
[INFO] Finished at: 2018-12-17T17:37:18+00:00
[INFO] Final Memory: 32M/177M
[INFO] ------------------------------------------------------------------------
[JENKINS] Archiving /var/jenkins_home/workspace/jgitver-maven-job-with-artifactory/pom.xml to fr.brouillard.oss/jgitver/0/jgitver-0.pom
[JENKINS] Archiving /var/jenkins_home/workspace/jgitver-maven-job-with-artifactory/target/jgitver-0.jar to fr.brouillard.oss/jgitver/0/jgitver-0.jar
channel stopped
Finished: SUCCESS
```

If I define a standard freestyle project in which I invoke maven on the CLI it works as expected but there is no integration with Artifactory.

So please provide more information on your setup and job definitions.

**Comment by McFoggy** [comment]
@dbcall2 can you please push a sample reproducer project (on github for example) that I could build on my local docker compose setup with Jenkins & Artifactory.

**Comment by McFoggy** [comment]
it works as expected using the following pipeline script

```
node {
    withMaven(maven: "mvn-3.3.9"){
        git "https://github.com/jgitver/jgitver.git"
        sh "mvn validate"
    }
}
```
here is the log

```
Started by user root
Running in Durability level: MAX_SURVIVABILITY
[Pipeline] node
Running on Jenkins in /var/jenkins_home/workspace/jgitver-pipeline
[Pipeline] {
[Pipeline] withMaven
[withMaven] Options: []
[withMaven] Available options: 
[withMaven] using JDK installation provided by the build agent
[withMaven] using Maven installation 'mvn-3.3.9'
[Pipeline] {
[Pipeline] git
Cloning the remote Git repository
Cloning repository https://github.com/jgitver/jgitver.git
 > git init /var/jenkins_home/workspace/jgitver-pipeline # timeout=10
Fetching upstream changes from https://github.com/jgitver/jgitver.git
 > git --version # timeout=10
 > git fetch --tags --progress https://github.com/jgitver/jgitver.git +refs/heads/*:refs/remotes/origin/*
 > git config remote.origin.url https://github.com/jgitver/jgitver.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://github.com/jgitver/jgitver.git # timeout=10
Fetching upstream changes from https://github.com/jgitver/jgitver.git
 > git fetch --tags --progress https://github.com/jgitver/jgitver.git +refs/heads/*:refs/remotes/origin/*
 > git rev-parse refs/remotes/origin/master^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/master^{commit} # timeout=10
Checking out Revision d50d2d8dafabd5497cfd019136e02eb441c438b4 (refs/remotes/origin/master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f d50d2d8dafabd5497cfd019136e02eb441c438b4
 > git branch -a -v --no-abbrev # timeout=10
 > git checkout -b master d50d2d8dafabd5497cfd019136e02eb441c438b4
Commit message: "use jgitver-maven-plugin 1.4.4"
First time build. Skipping changelog.
[Pipeline] sh
+ mvn validate
----- withMaven Wrapper script -----
Picked up JAVA_TOOL_OPTIONS: -Dmaven.ext.class.path="/var/jenkins_home/workspace/jgitver-pipeline@tmp/withMaven460f4b7d/pipeline-maven-spy.jar" -Dorg.jenkinsci.plugins.pipeline.maven.reportsFolder="/var/jenkins_home/workspace/jgitver-pipeline@tmp/withMaven460f4b7d" 
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T16:41:47+00:00)
Maven home: /var/jenkins_home/tools/hudson.tasks.Maven_MavenInstallation/mvn-3.3.9
Java version: 1.8.0_181, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "4.9.125-linuxkit", arch: "amd64", family: "unix"
[INFO] [jenkins-event-spy] Generate /var/jenkins_home/workspace/jgitver-pipeline@tmp/withMaven460f4b7d/maven-spy-20181217-175203-7201114546436076146564.log.tmp ...
[INFO] using jgitver configuration file: /var/jenkins_home/workspace/jgitver-pipeline/.mvn/jgitver.config.xml
[INFO] Scanning for projects...
[INFO] Using jgitver-maven-plugin [1.4.4] (sha1: f7ed5bc143004e2348d1a8ff3b938fc031825088)
[INFO] jgitver-maven-plugin is about to change project(s) version(s)
[INFO]     fr.brouillard.oss::jgitver::0 -> 0.8.7-SNAPSHOT
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building GIT versioning using jgit 0.8.7-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
...
```

**Comment by dbcall2** [comment]
Wow, you are awesome for jumping on this so quickly! It looks like the flavor of pipeline script you're using doesn't invoke the artifactory plugin directly. The artifactory-recommended approach is something like this: 

<pre>
def rtMaven = Artifactory.newMavenBuild()
rtMaven.tool = 'Maven339'
rtMaven.opts = '-DskipITs=true -DskipTests=true -Djacoco.skip=true'
mavenBuildInfo = rtMaven.run pom: config.pom, goals: config.mavenOpts + ' clean test'
</pre> 

It is when the artifactory scripted pipeline wrapper is used that the build fails. The afactory plugin is invoking the command line like so: 

<pre>
java -classpath /home/ciuser/jenkins/config/tools/hudson.tasks.Maven_MavenInstallation/Maven339/boot/* -Dmaven.home=/home/ciuser/jenkins/config/tools/hudson.tasks.Maven_MavenInstallation/Maven339 -Dmaven.conf=/home/ciuser/jenkins/config/tools/hudson.tasks.Maven_MavenInstallation/Maven339/conf -DbuildInfoConfig.propertiesFile=/home/ciuser/jenkins/config/workspace/ven-test-mb-build-trident_master@tmp/buildInfo7696432218401700949.properties -Dm3plugin.lib=/home/ciuser/jenkins/config/workspace/ven-test-mb-build-trident_master@tmp/cache/artifactory-plugin/2.16.2 -Dclassworlds.conf=/home/ciuser/jenkins/config/workspace/ven-test-mb-build-trident_master@tmp/classworlds6340635895835684671conf -Dmaven.multiModuleProjectDirectory=/home/ciuser/jenkins/config/workspace/ven-test-mb-build-trident_master -DskipITs=true -DskipTests=true -Djacoco.skip=true -Xmx512m org.codehaus.plexus.classworlds.launcher.Launcher -f pom.xml -X clean test
</pre>

I'm wondering what is different about how the artifactory pipeline plugin is invoking maven. Let me see if I can put together an example to trigger the issue, hang tight.

**Comment by dbcall2** [comment]
So here is my test setup... 

Install this guy as a shared lib first:
https://github.com/dbcall2/jenkins-shared-lib

The actual maven project w/extensions enabled lives here:
https://github.com/dbcall2/jgitver-artifactory-test

Then create a pipeline job that points at the jgitver-artifactory-test repo. If everything is loaded properly, the Jenkinsfile in the maven project repo should load the shared pipeline script. 

Please let me know how else I can assist. I'm not a fan of dumping issues on others, etc.

**Comment by McFoggy** [comment]
I reproduced with the following pipeline script, adapted from https://github.com/jfrog/project-examples/blob/master/jenkins-examples/pipeline-examples/maven-example/Jenkinsfile


```
node {
    def server = Artifactory.server('local')
    def rtMaven = Artifactory.newMavenBuild()
    def buildInfo

    stage ('Clone') {
        git url: 'https://github.com/jgitver/jgitver.git'
    }

    stage ('Artifactory configuration') {
        rtMaven.tool = 'mvn-3.3.9' // Tool name from Jenkins configuration
        rtMaven.deployer releaseRepo: 'libs-release-local', snapshotRepo: 'libs-snapshot-local', server: server
        rtMaven.resolver releaseRepo: 'libs-release', snapshotRepo: 'libs-snapshot', server: server
        buildInfo = Artifactory.newBuildInfo()
    }

    stage ('Exec Maven') {
        rtMaven.run pom: 'pom.xml', goals: 'clean install -DskipTests=true ', buildInfo: buildInfo
    }

    stage ('Publish build info') {
        server.publishBuildInfo buildInfo
    }
}
```

here is the output

```
...
[jgitver-pipeline] $ /docker-java-home/bin/java -classpath /var/jenkins_home/tools/hudson.tasks.Maven_MavenInstallation/mvn-3.3.9/boot/* -Dmaven.home=/var/jenkins_home/tools/hudson.tasks.Maven_MavenInstallation/mvn-3.3.9 -Dmaven.conf=/var/jenkins_home/tools/hudson.tasks.Maven_MavenInstallation/mvn-3.3.9/conf -DbuildInfoConfig.propertiesFile=/var/jenkins_home/workspace/jgitver-pipeline@tmp/buildInfo2931900882408034285.properties -DbuildInfoConfig.artifactoryResolutionEnabled=true -Dm3plugin.lib=/var/jenkins_home/workspace/jgitver-pipeline@tmp/cache/artifactory-plugin/2.16.2 -Dclassworlds.conf=/var/jenkins_home/workspace/jgitver-pipeline@tmp/classworlds1382898438349618258conf -Dmaven.multiModuleProjectDirectory=/var/jenkins_home/workspace/jgitver-pipeline org.codehaus.plexus.classworlds.launcher.Launcher -f pom.xml clean install -DskipTests=true
...
[main] INFO fr.brouillard.oss.jgitver.JGitverConfigurationComponent - using jgitver configuration file: /var/jenkins_home/workspace/jgitver-pipeline/.mvn/jgitver.config.xml
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - Scanning for projects...
[main] INFO fr.brouillard.oss.jgitver.JGitverExtension - Using jgitver-maven-plugin [1.4.4] (sha1: f7ed5bc143004e2348d1a8ff3b938fc031825088)
[main] INFO fr.brouillard.oss.jgitver.JGitverExtension - jgitver-maven-plugin is about to change project(s) version(s)
[main] INFO fr.brouillard.oss.jgitver.JGitverExtension -     fr.brouillard.oss::jgitver::0 -> 0.8.7-SNAPSHOT
[main] INFO org.jfrog.build.extractor.maven.BuildInfoRecorder - Initializing Artifactory Build-Info Recording
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger -                                                                         
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - ------------------------------------------------------------------------
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - Building GIT versioning using jgit 0.8.7-SNAPSHOT
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - ------------------------------------------------------------------------
[main] ERROR org.jfrog.build.extractor.maven.resolver.ArtifactoryEclipseRepositoryListener - Failed while enforcing Artifactory artifact resolver
org.codehaus.plexus.component.repository.exception.ComponentLookupException: java.util.NoSuchElementException
      role: org.jfrog.build.extractor.maven.resolver.ArtifactoryEclipseArtifactResolver
  roleHint: 
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:267)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:243)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:237)
	at org.jfrog.build.extractor.maven.resolver.ArtifactoryEclipseRepositoryListener.enforceArtifactoryResolver(ArtifactoryEclipseRepositoryListener.java:71)
	at org.jfrog.build.extractor.maven.resolver.ArtifactoryEclipseRepositoryListener.contextualize(ArtifactoryEclipseRepositoryListener.java:258)
	at org.eclipse.sisu.plexus.PlexusLifecycleManager.contextualize(PlexusLifecycleManager.java:282)
	at org.eclipse.sisu.plexus.PlexusLifecycleManager.activate(PlexusLifecycleManager.java:203)
	at org.eclipse.sisu.bean.BeanScheduler$Pending.activate(BeanScheduler.java:156)
	at org.eclipse.sisu.bean.BeanScheduler$Activator.onProvision(BeanScheduler.java:185)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:126)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:68)
```

what you can see is that jgitver was already involved in this build.

If you look at the maven command that is launched, then you can see the following plugin directory in use 

![image](https://user-images.githubusercontent.com/1119660/50111910-2dbb7a80-023e-11e9-8009-7a12bc9ab23e.png)

classworld conf is

```
jenkins@89bb515fcce6:~/workspace/jgitver-pipeline@tmp$ cat classworlds1382898438349618258conf
main is org.apache.maven.cli.MavenCli from plexus.core

set maven.home default ${user.home}/m2

[plexus.core]
load ${maven.home}/lib/*.jar
load ${m3plugin.lib}/*.jar
```

the plugin directory looks really suspect has it contains bad versions of artifacts!

I'd vote to open an issue to artifactory/jfrog.

Did you tried with another maven core extension ; I mean other than jgitver?

**Comment by McFoggy** [comment]
That's what I suspected, jgitver is not involved.

If you replace, in the above pipeline script, the jgitver git URL with 'https://github.com/takari/core-extensions-example.git' then you face the exact same issue. 

```
[main] INFO org.apache.maven.lifecycle.internal.LifecycleStarter - Using the SmartBuilder implementation with a thread count of 8
[main] INFO io.takari.maven.builder.smart.SmartBuilder - Task segments : [clean, install]
[main] INFO io.takari.maven.builder.smart.SmartBuilder - Build maximum degree of concurrency is 8
[main] INFO io.takari.maven.builder.smart.SmartBuilder - Total number of projects is 1
[BuilderThread 0] INFO io.takari.maven.builder.smart.SmartBuilder - STARTED build of project io.takari.maven:core-extension-example
[BuilderThread 0] INFO org.apache.maven.cli.event.ExecutionEventLogger -                                                                         
[BuilderThread 0] INFO org.apache.maven.cli.event.ExecutionEventLogger - ------------------------------------------------------------------------
[BuilderThread 0] INFO org.apache.maven.cli.event.ExecutionEventLogger - Building core-extensions-example 0.1.0-SNAPSHOT
[BuilderThread 0] INFO org.apache.maven.cli.event.ExecutionEventLogger - ------------------------------------------------------------------------
[BuilderThread 0] ERROR org.jfrog.build.extractor.maven.resolver.ArtifactoryEclipseRepositoryListener - Failed while enforcing Artifactory artifact resolver
org.codehaus.plexus.component.repository.exception.ComponentLookupException: java.util.NoSuchElementException
      role: org.jfrog.build.extractor.maven.resolver.ArtifactoryEclipseArtifactResolver
  roleHint: 
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:267)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:243)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:237)
	at org.jfrog.build.extractor.maven.resolver.ArtifactoryEclipseRepositoryListener.enforceArtifactoryResolver(ArtifactoryEclipseRepositoryListener.java:71)
	at org.jfrog.build.extractor.maven.resolver.ArtifactoryEclipseRepositoryListener.contextualize(ArtifactoryEclipseRepositoryListener.java:258)
	at org.eclipse.sisu.plexus.PlexusLifecycleManager.contextualize(PlexusLifecycleManager.java:282)
```
takari extensions are correctly loaded and used and it fails...

But this time jgitver is not used !!!

I think you have enough information to open an issue at jfrog now.

**Comment by dbcall2** [comment]
Perfect! That's my next avenue to pursue... I'll be working with JFrog here shortly. Thank you for entertaining this discussion as will likely help get the issue resolved much faster.

**Comment by reenberg** [comment]
@dbcall2, did you ever resolver anything with JFrog?
I'm having the exact same issues, just with another extension, and I found that [HAP-954](https://www.jfrog.com/jira/browse/HAP-954) had already been opened on this matter in July 2017, however no response as of yet.
