### ISSUE TITLE
Use next snapshot version when dirty

### ISSUE THREAD

**Issue by ssaarinen** [jgitver/jgitver-maven-plugin#56]
On master branch after creating an annotated tag (like v1.0) version resolves to 1.0 as expected. If I make some local changes and do not commit the version is still 1.0. This is problematic as I could accidentally publish these changes to a repo (mvn install or deploy) 

With useDirty=true the version changes to 1.0-dirty which is a bit better as it prevents the accidental override with deploy. But in my opinion it would be ideal if in this situation the version would already resolve to next snapshot (= 1.0.1-SNAPSHOT) like after I have commited the changes.

**Comment by McFoggy** [comment]
as you mentionned the dirty flag is there to figure out that you have locally modified files.

If you'd like to prevent yourself from doing bad things I'd tend to propose that you introduce some guards in your build tool. As you are using maven, introduce a check plugin running during _verify_ phase that will fail your build if you have uncommited changes ([scm:check-local-modification](https://maven.apache.org/components/scm/maven-scm-plugin/) will do that for you).

**Comment by ssaarinen** [comment]
This is actually not working so well with the useDirty. Always after a release I have to do a commit before I can get mvn to produce the right version number. And if I use the useDirty flag it even marks the snapshot versions dirty which is not what I want either. IMO in maven land it is fine for SNAPSHOTS to be inconsistent so the dirty flag in versioning is not required. I want to be able to depend on SNAPSHOTS in downstream projects and live with the fact that the changes might or might not be commited.

Would it be possible to add this kind of functionality (maybe with a cfg flag)? I could even give it a shot implementing it my self.

**Comment by McFoggy** [comment]
> Always after a release I have to do a commit before I can get mvn to produce the right version number.

which is a good practice for git. You can always do local commit.

> be possible to add this kind of functionality (maybe with a cfg flag)

with a config flag perhaps... but we should not introduce unwanted complexity for something that does not look to be a good practice and that has a simple workaround (a local commit)

**Comment by McFoggy** [comment]
closing as workaround and better practices exist.

**Comment by asyedin** [comment]
@McFoggy - what is the workaround / better practice? 
I have a CI build configuration which is always expected to build the latest snapshot from a branch, even though it wasn't changed after the latest annotated tag.
maven release plugin bumps the version up to the next snapshot in the perform phase, I'd love to see something similar in jgitver

**Comment by McFoggy** [comment]
- to prevent publishing dirty versions you can use [maven-enforcer-plugin](https://maven.apache.org/enforcer/maven-enforcer-plugin/), see the [usage in jgitver itself](https://github.com/jgitver/jgitver-maven-plugin/blob/master/pom.xml#L588-L592) for exemple
- for the computation of SNAPSHOT version on the commit with tag ; I'd reverse the question : do you really need that ? If there is no modification, no commit, after version X then latest version is X not X-SNAPSHOT

**Comment by asyedin** [comment]
thanks Matthieu
unfortunately, for the second part - yes I do. I'm trying to switch to your fantastic plugin a large application with dozens of maven projects and established CI/CD pipeline. Every other solution I've tried ends up being brittle and hacky, A simple mvn -DuseSnapshot that forces jgitver to calculate the version to the next snapshot would solve it perfectly.
