### ISSUE TITLE
Java 1.7

### ISSUE THREAD

**Issue by rfvermut** [jgitver/jgitver-maven-plugin#61]
I know it's EOL already but quite a few projects still using it. Would it be possible to build jre1.7 classified artifact in addition to 1.8?

**Comment by McFoggy** [comment]
Can you provide the corresponding PR?

It might probably need:
- retrolambda for jgitver & jgitver-maven-plugin
- additional jars with some `java7` classifier
- be sure that all other dependencies are java 7 friendly
- ...

**Comment by McFoggy** [comment]
no support provided, skipping request.
