### ISSUE TITLE
JGITVER_LATEST_VERSION is incorrectly calculated in install.sh

### ISSUE THREAD

**Issue by drivenbyentropy** [jgitver/jgitver-maven-plugin#63]
Hi,

When using either the `wget` or the `curl` method for installing the plugin, an incorrect `extension.xml` file is generated. Namely, the version tag states
```
<version>1.0.0,</version>
```
whereas it should be 
```
<version>1.0.0</version>
```

I believe this is due to `JGITVER_LATEST_VERSION` in the install.sh script being calculated incorrectly. 

In any case, thanks for this great plugin! Cheers.

**Comment by McFoggy** [comment]
@drivenbyentropy thanks for your support to this project.

Could you elaborate a bit more your non working environment?

I just retried on my windows 10 machine using the linux subsystem, and it went smoothly. Here are my versions:

````
$ uname -a
Linux MORLK964 3.4.0+ #1 PREEMPT Thu Aug 1 17:06:05 CST 2013 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty

$ wget --version
GNU Wget 1.15 built on linux-gnu.
...

$ curl --version
curl 7.35.0 (x86_64-pc-linux-gnu) libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3
...

$ python --version
Python 2.7.6
````

**Comment by drivenbyentropy** [comment]
@McFoggy sure. 

I investigated this further and it seems to by a python version issue. When running the command with python v2.7x I get
```bash
$ python --version
Python 2.7.12

$ curl -s "http://search.maven.org/solrsearch/select?q=g:%22fr.brouillard.oss%22+AND+a:%22jgitver-maven-plugin%22&core=gav&rows=1&wt=json" | python -mjson.tool  | grep '"v"' | tr -d '"' | tr -d ' ' | cut -d ':' -f 2
1.0.0
```

However, when using python 3.x, the output is 
```sh
$ python --version
Python 3.6.2 :: Anaconda, Inc.

$ curl -s "http://search.maven.org/solrsearch/select?q=g:%22fr.brouillard.oss%22+AND+a:%22jgitver-maven-plugin%22&core=gav&rows=1&wt=json" | python -mjson.tool  | grep '"v"' | tr -d '"' | tr -d ' ' | cut -d ':' -f 2
1.0.0,
```

I also tried this with a non-packaged version of python 3.x and the result is the same.

Hope this helps!

Just in case, here are the remaining environment details:
```bash
$ uname -a
Linux lmem05 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.4.1708 (Core)
Release:        7.4.1708
Codename:       Core

$ wget --version
GNU Wget 1.14 built on linux-gnu.

$ curl --version
curl 7.55.1 (x86_64-conda_cos6-linux-gnu) libcurl/7.55.1 OpenSSL/1.0.2l zlib/1.2.11 libssh2/1.8.0
```

**Comment by McFoggy** [comment]
@drivenbyentropy does the following provide the correct `1.0.0` answer using your python version?

````
curl -s "http://search.maven.org/solrsearch/select?q=g:%22fr.brouillard.oss%22+AND+a:%22jgitver-maven-plugin%22&core=gav&rows=1&wt=json" | python -mjson.tool  | grep '"v"' | tr -d '", ' | cut -d ':' -f 2
````

if yes then I'll push the changes to the install script

**Comment by drivenbyentropy** [comment]
@McFoggy  yes, this code produces the expected version string without a tailing comma.
