### ISSUE TITLE
Use commit timestamp in version

### ISSUE THREAD

**Issue by ottopoellath** [jgitver/jgitver-maven-plugin#65]
## Issue

**version**:  1.1.3

**usage context**:

- [ ] maven command line: 3.3.9

**Problem description**:

I would like to be able to include the commit timestamp in the version, using a configuration option called `useCommitTimestamp`. Combined with `useGitCommitId`, this would provide a version like `0.0.0-201711191102-8e918ddd`. Ideally, the timestamp format could be customised using another configuration option.

Background: I don't tag my code in git, but want each commit to produce a version suitable for continuous deployment. Using the commit is sufficient, but the versions cannot be sorted chronologically. So I want to prepend the commit timestamp to allow for chronological sorting of versions.

**Comment by McFoggy** [comment]
relates to jgitver/jgitver#22
