### ISSUE TITLE
Eclipse workspace project dependency resolution

### ISSUE THREAD

**Issue by ginkel** [jgitver/jgitver-maven-plugin#68]
## Issue

**version**: 1.1.4

**usage context**:

- [x] maven command line: 3.5.2
- [X] eclipse: Oxygen.1a Release (4.7.1a) / Build id: 20171005-1200 / OS: Linux, v.4.13.12-1-ARCH, x86_64 / gtk 3.22.26, WebKit 2.18.3

**Problem description**:

Let's say, I have two Maven projects:
- org.example:lib1:0.9.2-SNAPSHOT
- org.example:lib2:0.0.1-SNAPSHOT

Both get their version info using jgitver-maven-plugin, i.e., there is a recent tag 0.9.2 / 0.0.1 with at least one following commit.

org.example:lib2 has declared a dependency to org.example:lib1:0.9.2-SNAPSHOT.

When importing both projects into Eclipse using "Import Existing Maven projects" (with "Resolve workspace projects" checked on the import dialog), Eclipse fails to detect the project workspace dependency to org.example:lib1:0.9.2-SNAPSHOT, but instead creates a classpath version dependency to lib1's jar in ~/.m2/.

This causes that Eclipse does instantly exposes changes of lib1 to lib2 (e.g., when using "Run as Java Application") without a prior Maven build of lib1 on the command line.

Are you aware of a way to correctly resolve these workspace dependencies?

Merci!

**Comment by McFoggy** [comment]
I just created a sample project to demo how to do.
- clone: https://github.com/McFoggy/jgitver-samples
- follow instructions in [README](https://github.com/McFoggy/jgitver-samples/blob/master/with-deps/README.md)

Enjoy !

**Comment by ginkel** [comment]
Nice, thanks a lot! :-)
