### ISSUE TITLE
Nice to have jgitver.commit_distance

### ISSUE THREAD

**Issue by xeagle2** [jgitver/jgitver-maven-plugin#69]
It would be awesome to expose jgitver.commit_distance variable as well to reference it in project :)

**Comment by xeagle2** [comment]
Amazing, so it helps a lot! Thanks!

**Comment by McFoggy** [comment]
use 1.1.5 please.

Usage example in integration test [issue-69](https://github.com/jgitver/jgitver-maven-plugin/blob/master/src/it/issues/issue-69/pom.xml#L46)
