### ISSUE TITLE
"Cannot add two different pieces of metadata for" error when maven-deploy-plugin using -DdeployAtEnd

### ISSUE THREAD

**Issue by anthonime** [jgitver/jgitver-maven-plugin#72]
**version**: 0.4.0 and 1.1.6

**usage context**:

maven command line: 3.3.9
The command line is : 
`
mvn -U -B clean deploy -DskipTests=false -Dmaven.test.failure.ignore=true -DdeployAtEnd=true -Dgwt.draftCompile=true -Dgwt.compiler.strict=true -Dgwt.compiler.skip=false
`

**Problem description**:

We are building a multi-module Maven project, using jgitver maven plugin since version 0.4.0 (today we are at 1.1.6).
The build works correctly, and deployments of all artifacts on Nexus 3 works too, except when we use the `-DdeployAtEnd` config parameter.
In the case of `-DdeployAtEnd` config param, the "package" and "install" phases are ok, but the "deploy" phase fails on some arbitrary module, throwing the following logs: 
`
00:14:56.773 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.8.1:deploy (default-deploy) on project tv-restitution-engine-benchmark: Execution default-deploy of goal org.apache.maven.plugins:maven-deploy-plugin:2.8.1:deploy failed: Cannot add two different pieces of metadata for: project fr.mmt.tv.restitution.targets:tv-restitution-targets-model -> [Help 1]
`

Our Maven project contains more than 120 Maven modules. I've tried to use `-X` flag to enable debug trace but the resulting log is so big that it's impossible to even figure out where to look at for investigations.

Nevertheless, I'm sure the "bug" is related to jgitver because adding `-Djgitver.skip=true` make the deploy phase working as expected. Have you ever tried using `-DdeployAtEnd` parameter in a jgitver multimodule Maven project with success ? Do you have any idea ? Or even any hint on what I can do to provide you with more details ?

Thank you

**Comment by McFoggy** [comment]
I'll try to reproduce on a simplified project.

Otherwise you can try to execute with `-X` to activate maven traces and redirect output into a file.

**Comment by McFoggy** [comment]
@anthonime sorry I do not reproduce

```
git clone https://github.com/jgitver/jgitver-samples.git samples
cd samples/deploy-at-end
mvn clean deploy -DdeployAtEnd=true -DrepositoryURL=$PWD/../repository
```

**Comment by McFoggy** [comment]
neither with a multi-module project

```
git clone https://github.com/jgitver/jgitver-samples.git samples
cd samples/multi-deploy-at-end
mvn clean deploy -DdeployAtEnd=true -DrepositoryURL=$PWD/../repository
```

**Comment by anthonime** [comment]
Hi,

I've investigated a bit more, and could identify which one of my project modules is the culprit. 

We have one module that is using the `maven-shade-plugin` (v3.1.0) to create a uber-jar, containing all required dependencies. If I disable the `shade plugin`, the "`mvn clean deploy`" works perfeclty, using `-DdeployAtEnd=true`. If I enable this plugin, (even using the default plugin configuration), the deploy phase fails with the said error message. 
Note that disabling `deployAtEnd` works perfectly, or disabling `jgitver` also works, but of course, it's not what we want.
So I suspect that jgitver is not compatible with the way maven-shade-plugin works. 
I will have to replace the shade plugin with something else in order to fix our issue quickly.

**Comment by McFoggy** [comment]
@anthonime I just added a [multi-module project using shade plugin](https://github.com/jgitver/jgitver-samples) & jgitver and still I cannot reproduce.

1. please make modifications on this sample project (via a PR) to demo your issue. 
Without a reproducer case I cannot investigate further where your problem is.

2. share an extract of an execution with `-X` for the faulty module. Especially the debug output of the plugin that is failing could be interresting.

**Comment by anthonime** [comment]
@McFoggy sorry for late reply. Actually, we spent so much time investigating the problem, that we finally remove the "faulty" plugin (maven shade), and get another solution. 
I did not have time to investigate further.  I am going to close this bug right now, and I will reopen it one day if I have time to investigate more.

Thank you for your support !
