### ISSUE TITLE
support for configuration options from command line

### ISSUE THREAD

**Issue by edipal** [jgitver/jgitver-maven-plugin#75]
I think it would be nice to be able to overwrite some configuration options from command line. For example it might be useful when you build locally to use a different options.

Another possibility could be to add support for specifying a different configuration file from command line.

**Comment by McFoggy** [comment]
jgitver principle make the git history/data the truth of the computed version, allowing command line switches change the previous principle.

I am not against opening the system but can you explain the use case/need before?

**Comment by edipal** [comment]
i would like, in some cases (short features/bugfixes), to not include anything from the branch name in the version id
but i think we can do this using regex (when we include a certain marker in the branch name) - so we can distinguish between the two cases
