### ISSUE TITLE
Using the Maven Plugin makes IntelliJ Maven support useless

### ISSUE THREAD

**Issue by mirkosertic** [jgitver/jgitver-maven-plugin#8]
By enabling the Maven Plugin, IntelliJ Multi-Module Projects completely fail to resolve their depencencies within the IDE. I had to put the Plugin in a Profile and just use the Project-Version 0.0.0-SNAPSHOT for every module to make it working. On my build system i have enabled the Maven Profile which then uses the jgitver mechanism to determine the correct version.

**Comment by McFoggy** [comment]
Hi, this might be due to [IDEA-155733](https://youtrack.jetbrains.com/issue/IDEA-155733).

Can you please update your IDE to 2016.1.3 version that should contain the fix for IntellIJ & update to `jgitver-maven-plugin-0.1.1`.

**Comment by mirkosertic** [comment]
An IDE uprade for the whole team is not feasible.

For the moment we are working with a fixed version number "0.0.1-SNAPSHOT" and the mentioned profile, only enabled on our ci system.

**Comment by McFoggy** [comment]
> An IDE uprade for the whole team is not feasible.

Can you please at least verify that with the good IDEA version it works for you as expected?
I did it on my own with some personnal multi-modules but I would prefer that you ensure it works also for you in your context before closing the issue.

**Comment by mirkosertic** [comment]
IDEA 15.0.6, works with the Maven Profile, not with the documented default setup.

**Comment by McFoggy** [comment]
@mirkosertic thanks for your input. Do you have one up to date IDEA to test?

Meanwhile I'll document in a better way that previous versions of IDEA (< 2016.1.3) do not work with the plugin.

**Comment by esiqveland** [comment]
Seems to work for me with

```
IntelliJ IDEA 2016.1.3
Build #IU-145.1617, built on June 3, 2016
JRE: 1.8.0_76-release-b198 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

But my big maven project with many intermodule dependencies don't seem to like it much.

**Comment by McFoggy** [comment]
@esiqveland thanks for input but if you mean that there is something wrong in version propagation for your multi-module, please open another issue & provide an example if possible. Mirko problem is related to IDEA version ; we should not mix issues.

**Comment by esiqveland** [comment]
Yes, no problem 👍

**Comment by jschneider** [comment]
Be careful: It is also necessary to configure IntelliJ IDEA to _not_ use the bundled maven which is too old.
Settigs -> Build, Execution, Deployment -> Build Tools -> Maven.

One might add that to the plugin description...

**Comment by McFoggy** [comment]
@jschneider good notice, I'll add that to the documentation using #17

**Comment by mirkosertic** [comment]
The Maven Profile-based solution does not work as it breaks IntelliJ multi-module dependency resolution inside of the IDE, can't get it working for more than a "hello-world" example. Seems to be somwhow related to #10.

**Comment by McFoggy** [comment]
@mirkosertic can you please be a little bit more explicit on what does not work?  
If you have setup jgitver-maven-plugin in your pom inside a profile that is not active in Intellij IDEA in which way does it hurt your IDE?

**Comment by marcschumacher** [comment]
I am using the same version as @esiqveland mentioned and I get the following problem (in a single project pom): `Error:(2, 2) Could not initialize class org.eclipse.jgit.util.FS`
![2016-07-08_08-26-24](https://cloud.githubusercontent.com/assets/4214649/16679165/b124ad24-44e5-11e6-9594-7a00b17de718.png)

When I remove your extension it disappears.

**Comment by jschneider** [comment]
I am quite sure this can be fixed by configuring the maven version.
Go to:
Settings -> Build, Execution, Deployment -> Build Tools -> Maven

Configure the "Maven home directory" to something newer than 3.2.4(?)
IntelliJ Idea ships with a very old version of Maven.

**Comment by marcschumacher** [comment]
That did it! I thought I had already changed that, but I didn't. Thanks!

**Comment by McFoggy** [comment]
Great to hear it worked finally. Indeed the maven minimal version is important and unfortunately IDEA has a quite old version embedded.

**Comment by mirkosertic** [comment]
Well, finally it seems to work. 

IntelliJ 15.0.6
Maven 3.2.5
Using the Plugin with a Maven Profile

**Comment by McFoggy** [comment]
ok thanks for the feedback
