### ISSUE TITLE
How to introduce to an existing project

### ISSUE THREAD

**Issue by nickcodefresh** [jgitver/jgitver-maven-plugin#82]
Hi,

I have an existing project with a Maven POM version 1.1.54 and various tags in Git such as 1.0.0, 1.0.1 all the way up to 1.1.54. How do I introduce the plugin to this kind of project? Ideally I would like to carry on from 1.1.55 but understand that this probably isn't possible. In this case starting from 2.0.0 would be fine, but the plugin always seems to start from 0.0.0 (it always seems to pick the first Git tag, rather than the last).

Thanks

Nick

**Comment by McFoggy** [comment]
can you provide a bit more details on how your git history look like?

Otherwise, in general, I would say that when you want to tell/force jgitver to use a new version pattern, simply tag the last commit with a lightweight tag for the next version you want to work on.

So if your latest commit has a version of 1.1.55-SNAPSHOT (like I imagine it has) and that with jgitver you have a version of 0.0.0 then just tag last commit with `git tag v1.1.55` and now jgitver should report 1.1.55-SNAPSHOT as the version to use when running any maven command, `mvn validate` for example.

**Comment by nickcodefresh** [comment]
Thanks for the reply. If I show all of the annotated tags order by created date (`git for-each-ref --sort=taggerdate --format '%(refname) %(taggerdate)' refs/tags`) I see:
```
refs/tags/1.1.502 Thu Mar 8 01:05:06 2018 +0000
refs/tags/1.1.503 Thu Mar 8 14:43:13 2018 +0000
refs/tags/1.1.504 Fri Mar 9 01:04:49 2018 +0000
```
Running `mvn validate` locally I see:
```
[INFO] using jgitver configuration file: /Users/nicksmith/Documents/trunk/microservices/flex-javatemplate-service/.mvn/jgitver.config.xml
[INFO] Scanning for projects...
[INFO] Using jgitver-maven-plugin [1.2.1] (sha1: c28daa3dafbeeb7e21bdfc7bcda3c73ef7b480bd)
[INFO] jgitver-maven-plugin is about to change project(s) version(s)
[INFO]     com.ooyala.flex::flex-tbc::0 -> 1.1.505
[INFO]     com.ooyala.flex::flex-tbc-commons::0 -> 1.1.505
[INFO]     com.ooyala.flex::flex-tbc-client::0 -> 1.1.505
[INFO]     com.ooyala.flex::flex-tbc-acceptance-tests::0 -> 1.1.505
[INFO]     com.ooyala.flex::flex-tbc-service::0 -> 1.1.505
```
which looks right, but when I run this on Jenkins I see:
```
[INFO] using jgitver configuration file: /var/lib/jenkins/workspace/FlexJavaTemplate_master-CEOFRDDQJZ324VQFCCYDDYPI6DIJL5ROK3SYV4IAUHUXGRFUXVBA/.mvn/jgitver.config.xml
[INFO] Scanning for projects...
[INFO] Using jgitver-maven-plugin [1.2.1] (sha1: c28daa3dafbeeb7e21bdfc7bcda3c73ef7b480bd)
[INFO] jgitver-maven-plugin is about to change project(s) version(s)
[INFO]     com.ooyala.flex::flex-tbc::0 -> 0.0.0
[INFO]     com.ooyala.flex::flex-tbc-commons::0 -> 0.0.0
[INFO]     com.ooyala.flex::flex-tbc-client::0 -> 0.0.0
[INFO]     com.ooyala.flex::flex-tbc-acceptance-tests::0 -> 0.0.0
[INFO]     com.ooyala.flex::flex-tbc-service::0 -> 0.0.0
```
which is really odd. How can I be getting two different versions?

**Comment by nickcodefresh** [comment]
I should add that I'm using the Jenkins mutiplebranch pipeline plugin and a Jenkinsfile

**Comment by McFoggy** [comment]
- How is the checkout done in your setup?
- Do you checkout the SHA1 or the branch (see https://github.com/jgitver/jgitver-maven-plugin/wiki/jenkins-integration-multibranch-pipeline)?
- Are you able to make a shareable reproducer case ?

**Comment by nickcodefresh** [comment]
It was actually because Jenkins by default doesn't check out tags! When I changed the config to include them, it works as expected!

![screen shot 2018-03-12 at 12 26 01](https://user-images.githubusercontent.com/5837418/37283638-8d234474-25f0-11e8-8254-2edfad2447fc.png)

Thanks for your help

**Comment by McFoggy** [comment]
Perfect !
