### ISSUE TITLE
Add support for JDK9

### ISSUE THREAD

**Issue by edipal** [jgitver/jgitver-maven-plugin#84]
Please add support for JDK9.

At this time, running maven with JDK9 gives the following exception:
[WARNING] Error injecting: fr.brouillard.oss.jgitver.JGitverModelProcessor
java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException

**Comment by McFoggy** [comment]
please update to latest `1.2.1` version, java 9 support was added in `1.2.0`.

**Comment by edipal** [comment]
thx! that's great
