### ISSUE TITLE
Use of release branches

### ISSUE THREAD

**Issue by capitalfact** [jgitver/jgitver-maven-plugin#95]
## Issue
**version**: 1.3.0

**usage context**:

- [x] maven command line: 3.5.4

**Problem description**:
Note: This may not be an issue, rather the tool is not designed for my use case. Hopefully you can point me to the correct approach.

- I am required to use long standing release branches in order to prepare releases and split streams of release work activity.

- Master is at 0.0.1-SNAPSHOT (lightweight tag)
- Create branch: release/0.0.1, also at 0.0.1-SNAPSHOT (0.0.1-release_0.0.1-SNAPSHOT)
- Lightweight tag master at 0.0.2-SNAPSHOT
- release/0.0.1 now at 0.0.2-SNAPSHOT (0.0.2-release_0.0.1-SNAPSHOT)

Expected:
release/0.0.1 to remain at effective 0.0.1-SNAPSHOT.

**Replication steps**:

```
mvn archetype:generate -B -DarchetypeGroupId=org.apache.maven.archetypes -DarchetypeArtifactId=maven-archetype-quickstart   -DarchetypeVersion=1.1 -DgroupId=com.company -DartifactId=jgitver-tester -Dversion=0 -Dpackage=com.company.project
cd jgitver-tester
sh -c "$(wget https://raw.githubusercontent.com/jgitver/jgitver-maven-plugin/master/src/doc/scripts/install.sh -O -)"
mvn -N io.takari:maven:wrapper -Dmaven=3.5.4

echo '.idea'>>.gitignore
echo 'target'>>.gitignore
echo '*.iml'>>.gitignore

git init
git add .
git commit -m "Initial commit"
git tag 0.0.1-SNAPSHOT
./mvnw validate
```
version = 0.0.1-SNAPSHOT

Create release branch
```
git checkout -b release/0.0.1
./mvnw validate
```
version = 0.0.1-release_0.0.1-SNAPSHOT

Move master to 0.0.2-SNAPSHOT
```
git checkout master
git tag 0.0.2-SNAPSHOT
```

Release branch should remain at 0.0.1-SNAPSHOT
```
git checkout release/0.0.1
./mvnw validate
```
Expected version = 0.0.1-release_0.0.1-SNAPSHOT, Actual version = 0.0.2-release_0.0.1-SNAPSHOT

Is it possible to maintain versioning in release branches? 
And additionally is it possible to mark the release branch with the annotated tag for performing releases?

**Comment by McFoggy** [comment]
hi thanks for your detailed report.

jgitver in this version is not able to extract versions patterns out of branch names ; it will change in a later version I have plans for that.

For your use case and with current version I will do the following:
- do not use SNAPSHOT in tags
- configure jgitver to ignore branch name for release branches _(notice that master branch needs also a configuration because we are overriding the defaults)_
```
<configuration xmlns="http://jgitver.github.io/maven/configuration/1.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://jgitver.github.io/maven/configuration/1.0.0 https://jgitver.github.io/maven/configuration/jgitver-configuration-v1_0_0.xsd ">
    <mavenLike>true</mavenLike>
    <useDefaultBranchingPolicy>true</useDefaultBranchingPolicy>   <!-- uses jgitver#BranchingPolicy#DEFAULT_FALLBACK as fallback branch policy-->
    <branchPolicies>
        <branchPolicy>
            <pattern>(master)</pattern>                  <!-- regex pattern -->
            <!-- list of transformations to apply, if empty, defaults to REPLACE_UNEXPECTED_CHARS_UNDERSCORE, LOWERCASE_EN -->
            <transformations>                           
                <transformation>IGNORE</transformation> <!-- transformation name, one of jgitver#fr.brouillard.oss.jgitver.BranchingPolicy#BranchNameTransformations -->
            </transformations>
        </branchPolicy>
        <branchPolicy>
            <pattern>(release.*)</pattern>                  <!-- regex pattern -->
            <!-- list of transformations to apply, if empty, defaults to REPLACE_UNEXPECTED_CHARS_UNDERSCORE, LOWERCASE_EN -->
            <transformations>                           
                <transformation>IGNORE</transformation> <!-- transformation name, one of jgitver#fr.brouillard.oss.jgitver.BranchingPolicy#BranchNameTransformations -->
            </transformations>
        </branchPolicy>
    </branchPolicies>
</configuration>
```
- move lightweight tags to the first commit on the release branches
this is in my opinion one of the cases where moving a lightweight tag is valid
- use annotated tags on commits from the release branch

Hope it will cover your needs. If not not please come back for further explanations.

**Comment by capitalfact** [comment]
Thanks for the prompt response. I understand the solution, you may close this issue.
